// ===== Biolunet — Temario oficial (parte 2) =====
// 3) BIOLOGÍA DE PLANTAS I
CONTENIDO.plantas = {
  nombre: 'Biología de Plantas I', icono: '🌿',
  intro: 'De las briofitas a las gimnospermas, las plantas conquistaron la tierra firme y transformaron el planeta. Este recorrido sigue su evolución, sus ciclos y su diversidad.',
  unidades: [
    { nombre: 'Unidad I. Introducción al estudio de las arquegoniadas', temas: [
      { n:'Arquegoniadas',
        def:'Plantas que poseen arquegonios: brifitas, pteridofitas y gimnospermas (embriofitas no angiospermas).',
        exp:'El término agrupa a las plantas terrestres cuyo gametofito produce arquegonios; excluye a las angiospermas.',
        clave:['Arquegonio','Embriofitas','Gametofito'],
        flashcards:[['¿Qué caracteriza a las arquegoniadas?','Producen arquegonios (órgano sexual femenino).']] },
      { n:'Arquegonio',
        def:'Órgano sexual femenino multicelular de las plantas terrestres; contiene la ooesfera (gameto femenino).',
        exp:'Tiene forma de botella (cuello y vientre). Protege al gameto femenino y al embrión en desarrollo.',
        clave:['Órgano femenino','Ooesfera','Cuello y vientre'],
        examen:['Arquegonio = femenino; anteridio = masculino.'],
        flashcards:[['¿Qué gameto contiene el arquegonio?','La ooesfera (gameto femenino).']],
        preguntas:[['El arquegonio es el órgano sexual:',['Masculino','Femenino','Neutro','Asexual'],1,'Contiene el gameto femenino (ooesfera).']] },
      { n:'Anteridio',
        def:'Órgano sexual masculino que produce los gametos masculinos (anterozoides o espermatozoides).',
        exp:'En muchas arquegoniadas los anterozoides son flagelados y requieren agua para nadar hasta el arquegonio.',
        clave:['Órgano masculino','Anterozoides','Dependencia del agua'],
        examen:['La fecundación en briofitas y pteridofitas depende del agua (anterozoides flagelados).'],
        flashcards:[['¿Qué produce el anteridio?','Los gametos masculinos (anterozoides).']] }
    ]},
    { nombre: 'Unidad II. Origen de las plantas terrestres', temas: [
      { n:'Conquista del medio terrestre',
        def:'Proceso evolutivo por el que las plantas, a partir de algas verdes, colonizaron la tierra firme hace ~470 millones de años.',
        exp:'Adaptaciones clave: cutícula, estomas, tejidos de sostén, gametangios protegidos y embrión retenido (embriofitas).',
        clave:['Algas verdes','Cutícula','Estomas','Embriofitas'],
        examen:['Las plantas terrestres derivan de las algas verdes (carofitas).'],
        flashcards:[['¿De qué grupo derivan las plantas terrestres?','De las algas verdes (carofitas).']] },
      { n:'Micorrizas',
        def:'Simbiosis entre hongos y raíces que facilitó la colonización terrestre al mejorar la captación de nutrientes.',
        exp:'Se encuentran incluso en fósiles de las primeras plantas terrestres, lo que sugiere su papel temprano en la conquista de la tierra.',
        clave:['Simbiosis','Hongo-raíz','Fósforo','Coevolución'],
        flashcards:[['¿Cómo ayudaron las micorrizas a colonizar la tierra?','Mejoraron la absorción de agua y nutrientes de las primeras plantas.']] }
    ]},
    { nombre: 'Unidad III. Ciclos de vida', temas: [
      { n:'Alternancia de generaciones',
        def:'Ciclo de vida en el que se alternan una fase haploide (gametofito) y una diploide (esporofito).',
        exp:'El gametofito produce gametos por mitosis; el esporofito produce esporas por meiosis. El dominio de cada fase varía entre grupos.',
        clave:['Gametofito (n)','Esporofito (2n)','Meiosis','Mitosis'],
        cuadro:{titulo:'Fase dominante por grupo',head:['Grupo','Fase dominante'],filas:[['Briofitas','Gametofito (n)'],['Pteridofitas','Esporofito (2n)'],['Gimnospermas','Esporofito (2n)']]},
        examen:['En briofitas domina el gametofito; en el resto, el esporofito.'],
        flashcards:[['¿Qué fase domina en las briofitas?','El gametofito (haploide).']],
        preguntas:[['El esporofito produce esporas mediante:',['Mitosis','Meiosis','Gemación','Fisión'],1,'Las esporas se forman por meiosis.']] },
      { n:'Ciclos de vida',
        def:'Patrones de desarrollo: haplonte, diplonte y haplodiplonte (alternancia de generaciones), este último propio de las plantas.',
        exp:'La tendencia evolutiva en plantas es la reducción progresiva del gametofito y el predominio del esporofito.',
        clave:['Haplonte','Diplonte','Haplodiplonte'],
        flashcards:[['¿Qué ciclo tienen las plantas terrestres?','Haplodiplonte (alternancia de generaciones).']] },
      { n:'Heterosporia',
        def:'Producción de dos tipos de esporas: microsporas (masculinas) y megasporas (femeninas).',
        exp:'Es un paso clave hacia la semilla. La homosporia produce un solo tipo de espora; la heterosporia, dos.',
        clave:['Microspora','Megaspora','Paso hacia la semilla'],
        examen:['Heterosporia = dos tipos de espora; precede a la evolución de la semilla.'],
        flashcards:[['¿Qué dos esporas produce una planta heterospórica?','Microsporas (masculinas) y megasporas (femeninas).']] }
    ]},
    { nombre: 'Unidad IV. Sistemática vegetal', temas: [
      { n:'Sistemática vegetal',
        def:'Disciplina que clasifica y nombra a las plantas según sus relaciones evolutivas.',
        exp:'Usa caracteres morfológicos, anatómicos y moleculares. La nomenclatura binomial (género y especie) es su base.',
        clave:['Clasificación','Filogenia','Nomenclatura binomial'],
        flashcards:[['¿Qué es la nomenclatura binomial?','Nombrar cada especie con género y epíteto específico (p. ej. Pinus cembroides).']] }
    ]},
    { nombre: 'Unidad V. Biología de Briofitas', temas: [
      { n:'Briofitas',
        def:'Plantas terrestres no vasculares: musgos, hepáticas y antocerotas.',
        exp:'Carecen de tejidos conductores verdaderos (xilema/floema), dependen del agua para reproducirse y su fase dominante es el gametofito.',
        clave:['No vasculares','Musgos','Gametofito dominante','Dependen del agua'],
        ejemplos:['Los musgos que tapizan rocas húmedas y troncos.'],
        examen:['Briofitas = no vasculares, gametofito dominante.'],
        flashcards:[['¿Por qué las briofitas son pequeñas?','Carecen de tejidos vasculares para transportar agua a gran altura.']],
        preguntas:[['Las briofitas se caracterizan por:',['Ser vasculares','Tener semillas','No tener tejidos vasculares','Producir flores'],2,'Son plantas no vasculares.']] }
    ]},
    { nombre: 'Unidad VI. Histogénesis y teoría estelar', temas: [
      { n:'Teoría estelar',
        def:'Teoría que clasifica los tipos de estela (organización del tejido vascular en el tallo) y su evolución.',
        exp:'Tipos básicos: protostela (núcleo vascular sólido, más primitiva), sifonostela (con médula) y eustela (haces separados). Refleja tendencias evolutivas.',
        clave:['Estela','Protostela','Sifonostela','Eustela'],
        cuadro:{head:['Estela','Característica','Grado'],filas:[['Protostela','Xilema central sólido','Primitiva'],['Sifonostela','Con médula central','Intermedia'],['Eustela','Haces vasculares separados','Derivada']]},
        examen:['Protostela = más primitiva; eustela = más derivada.'],
        flashcards:[['¿Cuál es la estela más primitiva?','La protostela.']] }
    ]},
    { nombre: 'Unidad VII. Biología de Pteridofitas', temas: [
      { n:'Pteridofitas',
        def:'Plantas vasculares sin semilla: helechos y afines. Se reproducen por esporas y su esporofito es dominante.',
        exp:'Poseen xilema y floema verdaderos, raíces, tallos y hojas (frondes). Aún dependen del agua para la fecundación.',
        clave:['Vasculares sin semilla','Esporas','Frondes','Esporofito dominante'],
        examen:['Pteridofitas = primeras vasculares; sin semilla, con esporas.'],
        flashcards:[['¿Qué diferencia a pteridofitas de briofitas?','Las pteridofitas sí tienen tejido vascular.']] },
      { n:'Lycopodium',
        def:'Género de licofitas (“pinillos”) con hojas pequeñas (microfilos) dispuestas en espiral y esporangios en estróbilos.',
        exp:'Es homospórico. Representa un linaje muy antiguo de plantas vasculares.',
        clave:['Licofita','Micrfilos','Homospórico','Estróbilo'],
        flashcards:[['¿Lycopodium es homospórico o heterospórico?','Homospórico.']] },
      { n:'Selaginella',
        def:'Género de licofitas heterospóricas, con ligulas y microsporas/megasporas diferenciadas.',
        exp:'Su heterosporia lo hace importante para entender la evolución hacia la semilla. Algunas son “plantas de la resurrección”.',
        clave:['Licofita','Heterospórica','Lígula'],
        examen:['Selaginella es heterospórica (a diferencia de Lycopodium).'],
        flashcards:[['¿Por qué es notable Selaginella?','Es heterospórica, un paso hacia la semilla.']] },
      { n:'Equisetum',
        def:'Género de “colas de caballo”: plantas vasculares con tallos articulados y ricos en sílice.',
        exp:'Único género vivo de las esfenofitas; tiene hojas pequeñas en verticilos y esporangios en estróbilos apicales.',
        clave:['Cola de caballo','Tallo articulado','Sílice','Esfenofita'],
        flashcards:[['¿Nombre común de Equisetum?','Cola de caballo.']] }
    ]},
    { nombre: 'Unidad VIII. Paleobiología de criptógamas vasculares', temas: [
      { n:'Criptógamas vasculares fósiles',
        def:'Estudio de las plantas vasculares sin semilla del pasado, abundantes en el Paleozoico.',
        exp:'Los grandes bosques del Carbonífero (licofitas arbóreas como Lepidodendron, y Calamites) originaron los yacimientos de carbón.',
        clave:['Carbonífero','Lepidodendron','Calamites','Carbón'],
        examen:['El carbón mineral proviene de bosques de licofitas del Carbonífero.'],
        flashcards:[['¿Qué plantas formaron el carbón?','Licofitas arbóreas y afines del Carbonífero.']] }
    ]},
    { nombre: 'Unidad IX. Teorías sobre el origen de órganos vegetales', temas: [
      { n:'Teoría del teloma de Zimmermann',
        def:'Teoría que explica el origen de hojas, tallos y otros órganos a partir de ejes ramificados simples (telomas) de las primeras plantas.',
        exp:'Procesos evolutivos propuestos: superación (dominancia de un eje), planación (ramas en un plano) y fusión (unión para formar láminas foliares).',
        clave:['Teloma','Superación','Planación','Fusión'],
        examen:['La megáfila (hoja compleja) surge por planación + fusión de telomas.'],
        flashcards:[['¿Qué explica la teoría del teloma?','El origen evolutivo de los órganos vegetales a partir de ejes ramificados.']],
        preguntas:[['Según la teoría del teloma, las hojas grandes surgen por:',['Superación sola','Planación y fusión','Gemación','Meiosis'],1,'Planación y fusión de telomas forman la lámina foliar.']] }
    ]},
    { nombre: 'Unidad X. Biología de Gimnospermas', temas: [
      { n:'Gimnospermas',
        def:'Plantas con semilla “desnuda” (no encerrada en un fruto), generalmente sobre escamas de conos.',
        exp:'Incluyen coníferas, cícadas, Ginkgo y gnetofitas. Fueron dominantes en el Mesozoico. Fecundación independiente del agua (polen).',
        clave:['Semilla desnuda','Conos','Polen','Mesozoico'],
        examen:['Gimnosperma = semilla desnuda; angiosperma = semilla en fruto.'],
        flashcards:[['¿Qué significa “gimnosperma”?','Semilla desnuda, no encerrada en un fruto.']],
        preguntas:[['Una diferencia clave gimnospermas vs angiospermas es:',['Tener flores','Semilla desnuda vs en fruto','Ser no vasculares','Reproducirse por esporas'],1,'Las gimnospermas tienen la semilla desnuda.']] },
      { n:'Evolución de la semilla',
        def:'Innovación que integró heterosporia, retención de la megaspora y protección del embrión con reservas nutritivas.',
        exp:'La semilla liberó a las plantas de la dependencia del agua para reproducirse y permitió la dispersión y latencia del embrión.',
        clave:['Heterosporia','Óvulo','Embrión protegido','Latencia'],
        examen:['La semilla independiza la reproducción del agua.'],
        flashcards:[['¿Qué ventaja aportó la semilla?','Reproducción sin depender del agua y protección/latencia del embrión.']] },
      { n:'Coníferas',
        def:'Grupo más numeroso de gimnospermas: pinos, abetos, cipreses; con hojas aciculares y conos.',
        exp:'Dominan bosques templados y boreáles (taiga). Gran importancia maderera y ecológica.',
        clave:['Pinos','Conos','Hojas aciculares','Taiga'],
        ejemplos:['Los bosques de Pinus en las montañas de México.'],
        flashcards:[['¿Ejemplo típico de conífera?','El pino (Pinus).']] },
      { n:'Ginkgo biloba',
        def:'Única especie viva de su grupo; “fósil viviente” con hojas en forma de abanico y sexos separados.',
        exp:'Sus espermatozoides son flagelados (carácter primitivo). Muy resistente a la contaminación; usado en medicina y ornato.',
        clave:['Fósil viviente','Hoja en abanico','Dioica','Espermatozoide flagelado'],
        examen:['Ginkgo conserva espermatozoides flagelados, rasgo ancestral.'],
        flashcards:[['¿Por qué se llama a Ginkgo “fósil viviente”?','Es el único sobreviviente de un linaje muy antiguo casi sin cambios.']] }
    ]},
    { nombre: 'Unidad XI. Paleobiología de gimnospermas', temas: [
      { n:'Gimnospermas fósiles',
        def:'Estudio de gimnospermas extintas como las pteridóspermas (“helechos con semilla”) y cordaitales.',
        exp:'Las pteridóspermas son clave para entender el origen de la semilla; dominaron junto con otras gimnospermas en el Mesozoico.',
        clave:['Pteridóspermas','Cordaitales','Mesozoico'],
        flashcards:[['¿Qué son las pteridóspermas?','Gimnospermas fósiles conocidas como “helechos con semilla”.']] }
    ]},
    { nombre: 'Unidad XII. Importancia científica y económica', temas: [
      { n:'Importancia de las plantas',
        def:'Valor de briofitas, pteridofitas y gimnospermas para la ciencia, la economía y el ambiente.',
        exp:'Fuente de madera, resinas, medicinas y modelos evolutivos; los musgos (Sphagnum) forman turba y almacenan carbono.',
        clave:['Madera','Resinas','Turba','Bioindicadores'],
        flashcards:[['¿Uso económico del musgo Sphagnum?','Formación de turba y sustrato hortícola.']] }
    ]},
    { nombre: 'Unidad XIII. Cultivo y conservación', temas: [
      { n:'Cultivo y conservación',
        def:'Estrategias para propagar y proteger las plantas sin flores y sus hábitats.',
        exp:'Incluye bancos de germoplasma, jardines botánicos, propagación de esporas y protección de bosques de coníferas amenazados.',
        clave:['Germoplasma','Jardín botánico','Conservación in situ'],
        examen:['Conservación in situ (en su hábitat) vs ex situ (bancos, jardines).'],
        flashcards:[['¿Diferencia conservación in situ vs ex situ?','In situ = en su hábitat; ex situ = fuera (bancos, jardines).']] }
    ]}
  ]
};

// 4) BIOLOGÍA MOLECULAR DE LA CÉLULA II
CONTENIDO.molecular = {
  nombre: 'Biología Molecular de la Célula II', icono: '🧫',
  intro: 'La célula vive gracias a fronteras selectivas y a fábricas de energía. Aquí exploramos cómo la membrana controla lo que entra y sale, y cómo mitocondrias y cloroplastos transforman la energía.',
  unidades: [
    { nombre: 'I. La Membrana Plasmática', temas: [
      { n:'Bicapas de lípidos',
        def:'Estructura de doble capa formada por fosfolípidos anfipáticos, base de todas las membranas biológicas.',
        exp:'Las cabezas hidrofílicas quedan hacia el agua y las colas hidrofóbicas hacia el interior. Es una barrera semipermeable y autoensamblante.',
        clave:['Fosfolípido','Anfipático','Hidrofílico/hidrofóbico','Semipermeable'],
        examen:['Las cabezas polares miran al agua; las colas apolares, al centro.'],
        flashcards:[['¿Por qué los fosfolípidos forman bicapas?','Por ser anfipáticos: cabezas al agua, colas al interior.']],
        preguntas:[['La bicapa lipídica es semipermeable porque:',['Deja pasar todo','Su interior hidrofóbico frena sustancias polares','Es rígida','No tiene proteínas'],1,'El núcleo hidrofóbico bloquea el paso libre de moléculas polares.']] },
      { n:'Modelo de mosaico fluido',
        def:'Modelo de Singer y Nicolson (1972) que describe la membrana como una bicapa fluida con proteínas embebidas que se desplazan.',
        exp:'Los lípidos y proteínas se mueven lateralmente; el colesterol regula la fluidez. Es dinámico, no rígido.',
        clave:['Singer-Nicolson','Fluidez','Colesterol','Mosaico'],
        examen:['El colesterol modula la fluidez de la membrana.'],
        flashcards:[['¿Qué propone el modelo de mosaico fluido?','Una bicapa fluida con proteínas que se desplazan lateralmente.']] },
      { n:'Proteínas integrales',
        def:'Proteínas que atraviesan total o parcialmente la bicapa, ancladas por regiones hidrofóbicas.',
        exp:'Muchas son transmembranales y funcionan como canales, transportadores o receptores. Solo se extraen con detergentes.',
        clave:['Transmembranal','Hidrofóbica','Canal/receptor'],
        cuadro:{head:['Tipo','Ubicación','Extracción'],filas:[['Integral','Embebida/atraviesa','Con detergentes'],['Periférica','Superficie','Con sales/pH']]},
        flashcards:[['¿Cómo se extraen las proteínas integrales?','Solo con detergentes que rompen la bicapa.']] },
      { n:'Proteínas periféricas',
        def:'Proteínas unidas débilmente a la superficie de la membrana o a proteínas integrales.',
        exp:'No penetran la bicapa; se separan con cambios de pH o fuerza iónica. Participan en señalización y soporte del citoesqueleto.',
        clave:['Superficie','Unión débil','Señalización'],
        flashcards:[['¿Las proteínas periféricas atraviesan la membrana?','No; se unen a la superficie.']] },
      { n:'Carbohidratos membranales',
        def:'Azúcares unidos a lípidos (glucolípidos) o proteínas (glucoproteínas) en la cara externa de la membrana.',
        exp:'Forman el glucocálix; participan en reconocimiento celular, adhesión e inmunidad (p. ej. grupos sanguíneos).',
        clave:['Glucocálix','Reconocimiento','Glucoproteína'],
        examen:['Los carbohidratos siempre están en la cara EXTERNA de la membrana.'],
        flashcards:[['¿Función del glucocálix?','Reconocimiento y adhesión celular.']] },
      { n:'Membrana del eritrocito',
        def:'Modelo clásico de estudio de membranas; su citoesqueleto de espectrina le da forma bicóncava y flexibilidad.',
        exp:'Proteínas como la banda 3 (intercambiador de aniones) y la glucoforina son referentes del estudio de membranas.',
        clave:['Espectrina','Banda 3','Glucoforina','Bicóncava'],
        flashcards:[['¿Qué proteína da forma al eritrocito?','La espectrina (citoesqueleto).']] },
      { n:'Transporte pasivo',
        def:'Movimiento de sustancias a favor de su gradiente, sin gasto de energía.',
        exp:'Incluye difusión simple, difusión facilitada (por canales/transportadores) y ósmosis.',
        clave:['A favor del gradiente','Sin ATP','Difusión'],
        examen:['Transporte pasivo = a favor del gradiente, sin ATP.'],
        flashcards:[['¿¿El transporte pasivo gasta energía?','No; ocurre a favor del gradiente.']],
        preguntas:[['El transporte pasivo se caracteriza por:',['Gastar ATP','Ir a favor del gradiente','Ir contra el gradiente','Requerir bombas'],1,'Va a favor del gradiente sin gasto de energía.']] },
      { n:'Transporte activo',
        def:'Movimiento de sustancias en contra de su gradiente, con gasto de energía (ATP).',
        exp:'Puede ser primario (usa ATP directamente, como la bomba Na⁺/K⁺) o secundario (aprovecha un gradiente creado, cotransporte).',
        clave:['Contra el gradiente','ATP','Primario/secundario'],
        examen:['Transporte activo = contra gradiente + gasto de energía.'],
        flashcards:[['¿Diferencia clave transporte activo vs pasivo?','El activo va contra el gradiente y gasta ATP.']] },
      { n:'Bomba sodio-potasio',
        def:'Proteína de transporte activo que expulsa 3 Na⁺ e introduce 2 K⁺ por cada ATP hidrolizado.',
        exp:'Mantiene el potencial de membrana y el volumen celular; es electrogénica (saca más carga de la que mete).',
        clave:['3 Na⁺ out / 2 K⁺ in','ATPasa','Potencial de membrana'],
        examen:['Bomba Na⁺/K⁺: 3 Na⁺ fuera, 2 K⁺ dentro por cada ATP.'],
        flashcards:[['¿Proporción de iones de la bomba Na/K?','3 Na⁺ hacia afuera y 2 K⁺ hacia adentro por ATP.']],
        preguntas:[['La bomba Na⁺/K⁺ mueve por cada ATP:',['2 Na fuera, 3 K dentro','3 Na fuera, 2 K dentro','1 Na, 1 K','3 K fuera, 2 Na dentro'],1,'3 Na⁺ hacia afuera y 2 K⁺ hacia adentro.']] },
      { n:'Canales iónicos',
        def:'Proteínas integrales que forman poros selectivos para el paso rápido de iones a favor de su gradiente.',
        exp:'Pueden abrirse por voltaje, ligando o estímulo mecánico. Esenciales en la transmisión nerviosa.',
        clave:['Poro selectivo','Voltaje/ligando','Transporte pasivo'],
        flashcards:[['¿Los canales iónicos gastan ATP?','No; permiten flujo pasivo selectivo de iones.']] },
      { n:'Cotransporte',
        def:'Transporte activo secundario que acopla el movimiento de dos sustancias: simporte (misma dirección) o antiporte (direcciones opuestas).',
        exp:'Aprovecha el gradiente de un ión (a menudo Na⁺) para mover otra molécula contra su gradiente.',
        clave:['Simporte','Antiporte','Secundario'],
        cuadro:{head:['Tipo','Dirección'],filas:[['Simporte','Ambas sustancias en el mismo sentido'],['Antiporte','En sentidos opuestos']]},
        examen:['Simporte = mismo sentido; antiporte = sentidos opuestos.'],
        flashcards:[['¿Qué es el simporte?','Cotransporte de dos sustancias en la misma dirección.']] },
      { n:'Ósmosis',
        def:'Difusión del agua a través de una membrana semipermeable desde donde hay menos solutos hacia donde hay más.',
        exp:'Determina si una célula se hincha o se encoge según el medio: hipotónico, isotónico o hipertónico.',
        clave:['Agua','Semipermeable','Hipo/iso/hipertónico'],
        cuadro:{head:['Medio','Efecto en la célula'],filas:[['Hipotónico','Entra agua: se hincha'],['Isotónico','Sin cambio neto'],['Hipertónico','Sale agua: se encoge']]},
        examen:['En medio hipertónico la célula pierde agua (crenación).'],
        flashcards:[['¿Qué le pasa a un eritrocito en agua pura (hipotónica)?','Entra agua y puede estallar (hemólisis).']],
        preguntas:[['En un medio hipertónico, la célula:',['Se hincha','No cambia','Pierde agua','Gana solutos'],2,'Sale agua hacia el medio con más solutos.']] },
      { n:'Endocitosis',
        def:'Proceso por el que la célula introduce material envolviéndolo con la membrana para formar una vesícula.',
        exp:'Tipos: fagocitosis (partículas sólidas), pinocitosis (líquidos) y endocitosis mediada por receptor.',
        clave:['Fagocitosis','Pinocitosis','Mediada por receptor','Vesícula'],
        examen:['Fagocitosis = sólidos; pinocitosis = líquidos.'],
        flashcards:[['¿Diferencia fagocitosis vs pinocitosis?','Fagocitosis capta sólidos; pinocitosis, líquidos.']] },
      { n:'Exocitosis',
        def:'Proceso por el que la célula expulsa material fusionando vesículas con la membrana plasmática.',
        exp:'Permite secretar hormonas, neurotransmisores y enzimas, y renovar la membrana.',
        clave:['Secreción','Vesícula','Fusión'],
        flashcards:[['¿Qué permite la exocitosis?','Secretar sustancias y añadir membrana a la superficie.']] },
      { n:'Fusión de membranas',
        def:'Unión de dos bicapas en una sola, mediada por proteínas como las SNARE.',
        exp:'Es esencial en exocitosis, tráfico vesicular y entrada de algunos virus envueltos.',
        clave:['SNARE','Tráfico vesicular','Virus envueltos'],
        flashcards:[['¿Qué proteínas median la fusión de vesículas?','Las proteínas SNARE.']] }
    ]},
    { nombre: 'II. Mitocondrias y Cloroplastos', temas: [
      { n:'ATP y bioenergética',
        def:'El ATP es la “moneda energética” de la célula; su hidrólisis libera energía para el trabajo celular.',
        exp:'Se forma por fosforilación del ADP. La bioenergética estudia los flujos de energía y el papel del ΔG (energía libre).',
        clave:['ATP','ADP + Pi','ΔG','Acoplamiento'],
        examen:['Reacciones exergónicas (ΔG<0) impulsan endergónicas por acoplamiento con ATP.'],
        flashcards:[['¿Por qué el ATP es la moneda energética?','Su hidrólisis libera energía que acopla a procesos celulares.']],
        preguntas:[['El ATP libera energía al:',['Sintetizarse','Hidrolizarse a ADP + Pi','Oxidar glucosa','Reducir NAD'],1,'La hidrólisis de ATP a ADP + Pi libera energía.']] },
      { n:'Reacciones redox',
        def:'Reacciones de oxidación-reducción: transferencia de electrones de un donador (se oxida) a un aceptor (se reduce).',
        exp:'En el metabolismo, coenzimas como NAD⁺ y FAD transportan electrones. “LEO the lion says GER”: pierde electrones = oxidación.',
        clave:['Oxidación','Reducción','NAD⁺/FAD','Electrones'],
        examen:['Oxidar = perder e⁻; reducir = ganar e⁻.'],
        flashcards:[['¿Qué le pasa a una molécula que se oxida?','Pierde electrones.']] },
      { n:'Glucólisis',
        def:'Vía citoplasmática que degrada una glucosa en dos piruvatos, con ganancia neta de 2 ATP y 2 NADH.',
        exp:'No requiere oxígeno. Es la primera etapa de la respiración y una vía muy antigua y universal.',
        clave:['Glucosa→2 piruvato','2 ATP neto','2 NADH','Citoplasma'],
        examen:['Glucólisis: rinde 2 ATP netos y 2 NADH, en el citoplasma.'],
        flashcards:[['¿Cuántos ATP netos rinde la glucólisis?','2 ATP netos.']],
        preguntas:[['La glucólisis ocurre en:',['La mitocondria','El citoplasma','El núcleo','El cloroplasto'],1,'Ocurre en el citoplasma.']] },
      { n:'Fermentación',
        def:'Vía anaeróbica que regenera NAD⁺ a partir de piruvato cuando falta oxígeno.',
        exp:'Puede ser láctica (músculo, bacterias del yogur) o alcohólica (levaduras: etanol + CO₂). No produce ATP adicional.',
        clave:['Anaeróbica','Láctica','Alcohólica','Regenera NAD⁺'],
        cuadro:{head:['Tipo','Producto','Organismo'],filas:[['Láctica','Ácido láctico','Músculo, bacterias'],['Alcohólica','Etanol + CO₂','Levaduras']]},
        examen:['La fermentación sirve para regenerar NAD⁺, no para producir ATP extra.'],
        flashcards:[['¿¿Para qué sirve la fermentación?','Regenerar NAD⁺ y permitir que continúe la glucólisis sin oxígeno.']] },
      { n:'Ciclo de Krebs',
        def:'Ciclo del ácido cítrico: oxida el acetil-CoA en la matriz mitocondrial, liberando CO₂ y produciendo NADH, FADH₂ y GTP/ATP.',
        exp:'Por cada acetil-CoA: 3 NADH, 1 FADH₂, 1 GTP y 2 CO₂. Es el eje central del metabolismo aeróbico.',
        clave:['Matriz mitocondrial','Acetil-CoA','3 NADH/1 FADH₂','CO₂'],
        examen:['El ciclo de Krebs ocurre en la matriz mitocondrial.'],
        flashcards:[['¿Dónde ocurre el ciclo de Krebs?','En la matriz mitocondrial.']],
        preguntas:[['Por cada acetil-CoA el ciclo de Krebs produce:',['1 NADH','3 NADH y 1 FADH₂','2 ATP','5 FADH₂'],1,'3 NADH, 1 FADH₂ y 1 GTP por vuelta.']] },
      { n:'Cadena de transporte de electrones',
        def:'Serie de complejos en la membrana mitocondrial interna que transfieren electrones del NADH/FADH₂ al oxígeno.',
        exp:'La energía liberada bombea protones al espacio intermembrana, creando un gradiente electroquímico. El O₂ es el aceptor final.',
        clave:['Membrana interna','Complejos I-IV','O₂ aceptor final','Gradiente de H⁺'],
        examen:['El aceptor final de electrones es el oxígeno, que forma agua.'],
        flashcards:[['¿Cuál es el aceptor final de electrones?','El oxígeno (O₂), que se reduce a agua.']] },
      { n:'Fosforilación oxidativa',
        def:'Síntesis de ATP impulsada por el gradiente de protones a través de la ATP sintasa (quimiósmosis).',
        exp:'Los protones vuelven a la matriz por la ATP sintasa, que gira y fosforila ADP. Rinde la mayor parte del ATP de la respiración.',
        clave:['ATP sintasa','Quimisosis','Gradiente de H⁺','~34 ATP'],
        examen:['La ATP sintasa aprovecha el gradiente de H⁺ para producir ATP (teoría quimiosmótica de Mitchell).'],
        flashcards:[['¿Qué enzima produce ATP en la fosforilación oxidativa?','La ATP sintasa.']],
        preguntas:[['La ATP sintasa produce ATP usando:',['ATP','El gradiente de protones','O₂ directamente','Glucosa'],1,'Usa el gradiente de H⁺ (quimiósmosis).']] },
      { n:'Vía de las pentosas fosfato',
        def:'Vía alternativa a la glucólisis que produce NADPH y ribosa-5-fosfato.',
        exp:'El NADPH sirve para biosíntesis y defensa antioxidante; la ribosa, para nucleótidos. Es citoplasmática.',
        clave:['NADPH','Ribosa-5-P','Biosntesis','Citoplasma'],
        examen:['Pentosas fosfato: fuente de NADPH y de ribosa para nucleótidos.'],
        flashcards:[['¿Dos productos clave de la vía de pentosas fosfato?','NADPH y ribosa-5-fosfato.']] },
      { n:'Gluconeogénesis',
        def:'Síntesis de glucosa a partir de precursores no glucdicos (lactato, aminoácidos, glicerol).',
        exp:'Ocurre sobre todo en hígado durante el ayuno. No es la simple inversa de la glucólisis: usa enzimas propias en los pasos irreversibles.',
        clave:['Hígado','Ayuno','Precursores no glucdicos'],
        examen:['Gluconeogénesis ≠ glucólisis inversa (tiene 3 pasos con enzimas distintas).'],
        flashcards:[['¿¿Qué hace la gluconeogénesis?','Sintetiza glucosa a partir de precursores no glucdicos.']] },
      { n:'Glucógeno',
        def:'Polímero ramificado de glucosa que almacena energía en hígado y músculo.',
        exp:'La glucógenogénesis lo forma y la glucógenólisis lo degrada. El del hígado regula la glucemia; el del músculo, la actividad.',
        clave:['Reserva de glucosa','Hígado/músculo','Síntesis/degradación'],
        flashcards:[['¿Para qué sirve el glucógeno hepático?','Mantener estable la glucosa en sangre.']] },
      { n:'β-oxidación de ácidos grasos',
        def:'Degradación de ácidos grasos en la matriz mitocondrial que produce acetil-CoA, NADH y FADH₂.',
        exp:'Cada ronda corta 2 carbonos del ácido graso. Es una fuente muy rica de energía por gramo (más que los azúcares).',
        clave:['Ácidos grasos','Acetil-CoA','Matriz mitocondrial'],
        examen:['La β-oxidación corta el ácido graso de 2 en 2 carbonos, generando acetil-CoA.'],
        flashcards:[['¿Qué produce la β-oxidación?','Acetil-CoA, NADH y FADH₂ a partir de ácidos grasos.']] },
      { n:'Cloroplastos',
        def:'Organelos de las células vegetales donde ocurre la fotosíntesis; contienen clorofila en los tilacoides.',
        exp:'Tienen doble membrana, estroma y tilacoides apilados en grana. Son de origen endosimbiótico (cianobacterias).',
        clave:['Tilacoides','Grana','Estroma','Endosimbiosis'],
        examen:['Fase luminosa en tilacoides; ciclo de Calvin en el estroma.'],
        flashcards:[['¿Dónde está la clorofila?','En las membranas de los tilacoides.']] },
      { n:'Fotosíntesis',
        def:'Proceso que convierte CO₂ y agua en glucosa usando energía luminosa, liberando O₂.',
        exp:'Tiene fase luminosa (produce ATP y NADPH, libera O₂ al romper agua) y fase oscura o ciclo de Calvin (fija CO₂).',
        clave:['Fase luminosa','Fase oscura','O₂','ATP + NADPH'],
        examen:['El O₂ liberado proviene del agua, no del CO₂.'],
        flashcards:[['¿De dónde proviene el O₂ de la fotosíntesis?','De la fotólisis del agua.']],
        preguntas:[['El oxígeno liberado en la fotosíntesis proviene de:',['El CO₂','El agua','La glucosa','El ATP'],1,'Proviene de romper el agua (fotólisis).']] },
      { n:'Ciclo de Calvin',
        def:'Vía del estroma que fija CO₂ usando ATP y NADPH para producir azúcares (fase oscura).',
        exp:'La enzima RuBisCO fija el CO₂ a la RuBP. Tras varias vueltas se forma una molécula de azúcar (G3P).',
        clave:['RuBisCO','RuBP','G3P','Estroma'],
        examen:['La RuBisCO es la enzima que fija el CO₂ en el ciclo de Calvin.'],
        flashcards:[['¿Qué enzima fija el CO₂ en el ciclo de Calvin?','La RuBisCO.']] },
      { n:'Plantas C3, C4 y CAM',
        def:'Estrategias de fijación de CO₂ adaptadas al clima: C3 (estándar), C4 (concentra CO₂) y CAM (fija de noche).',
        exp:'C4 y CAM reducen la fotorrespiración en ambientes cálidos/secos. El maíz es C4; los cactus, CAM.',
        clave:['C3','C4','CAM','Fotorrespiración'],
        cuadro:{head:['Tipo','Ventaja','Ejemplo'],filas:[['C3','Clima templado','Trigo, arroz'],['C4','Clima cálido, menos fotorrespiración','Maíz, caña'],['CAM','Árido, fija de noche','Cactus, agave']]},
        examen:['Las plantas C4 concentran CO₂ para minimizar la fotorrespiración.'],
        flashcards:[['¿¿Qué tipo fotosintético es el maíz?','C4.']],
        preguntas:[['Las plantas CAM fijan CO₂ principalmente:',['De día','De noche','Nunca','Solo con lluvia'],1,'Abren estomas de noche para evitar pérdida de agua.']] },
      { n:'Metabolismo del nitrógeno',
        def:'Conjunto de vías que incorporan el nitrógeno a moléculas orgánicas (aminoácidos, nucleótidos).',
        exp:'Incluye fijación de N₂ por bacterias, nitrificación y asimilación como amonio y nitrato en las plantas.',
        clave:['Fijación de N₂','Nitrato/amonio','Asimilación'],
        examen:['Solo ciertas bacterias fijan N₂ atmosférico (nitrogenasa).'],
        flashcards:[['¿¿Quién fija el nitrógeno atmosférico?','Bacterias con la enzima nitrogenasa.']] },
      { n:'Integración metabólica',
        def:'Coordinación de las vías de carbohidratos, lípidos y proteínas según el estado energético del organismo.',
        exp:'Hormonas como insulina y glucagón regulan si se almacena o se moviliza energía. El acetil-CoA es el punto de encuentro central.',
        clave:['Insulina/glucagón','Acetil-CoA','Ayuno/alimentación'],
        examen:['El acetil-CoA conecta el metabolismo de azúcares, grasas y proteínas.'],
        flashcards:[['¿Molécula que integra el metabolismo energético?','El acetil-CoA.']] }
    ]}
  ]
};

// 5) CIENCIAS DE LA TIERRA
CONTENIDO.tierra = {
  nombre: 'Ciencias de la Tierra', icono: '🌍',
  intro: 'El planeta vivo se explica por sus capas, sus placas en movimiento y los ciclos que moldean su superficie a lo largo del tiempo geológico. Aquí conectamos la geología con la vida.',
  unidades: [
    { nombre: 'Unidad I. Origen y estructura de la Tierra', temas: [
      { n:'Origen de la Tierra',
        def:'La Tierra se formó hace ~4 600 millones de años por acreción de material del disco protoplanetario alrededor del Sol.',
        exp:'El calor de impactos y desintegración radiactiva fundió el planeta, permitiendo su diferenciación en capas por densidad.',
        clave:['Acreción','4 600 M.a.','Diferenciación','Disco protoplanetario'],
        examen:['La Tierra tiene ~4 600 millones de años.'],
        flashcards:[['¿Cómo se formó la Tierra?','Por acreción de material del disco protoplanetario, hace ~4 600 M.a.']],
        preguntas:[['La edad aproximada de la Tierra es:',['4 600 millones de años','1 000 millones','13 800 millones','500 millones'],0,'Unos 4 600 millones de años.']] },
      { n:'Estructura interna',
        def:'La Tierra se organiza en capas: corteza, manto y núcleo (externo líquido e interno sólido).',
        exp:'Por composición: corteza, manto, núcleo. Por comportamiento mecánico: litosfera (rígida), astenosfera (dúctil), mesosfera, núcleo.',
        clave:['Corteza','Manto','Núcleo','Litosfera/astenosfera'],
        cuadro:{titulo:'Capas por composición',head:['Capa','Estado','Composición'],filas:[['Corteza','Sólida','Silicatos ligeros'],['Manto','Sólido dúctil','Silicatos de Fe/Mg'],['Núcleo ext.','Líquido','Fe-Ni'],['Núcleo int.','Sólido','Fe-Ni']]},
        examen:['El campo magnético se genera en el núcleo externo líquido (Fe-Ni).'],
        flashcards:[['¿Qué capa genera el campo magnético?','El núcleo externo líquido (hierro-níquel en movimiento).']],
        diagrama:{centro:'Interior de la Tierra',ramas:['Corteza','Manto','Núcleo externo (líquido)','Núcleo interno (sólido)']} }
    ]},
    { nombre: 'Unidad II. Minerales y rocas', temas: [
      { n:'Minerales',
        def:'Sólidos naturales, inorgánicos, con composición química definida y estructura cristalina ordenada.',
        exp:'Se identifican por dureza (escala de Mohs), brillo, color, raya, exfoliación y densidad.',
        clave:['Cristalino','Escala de Mohs','Exfoliación'],
        examen:['Escala de Mohs: del talco (1) al diamante (10).'],
        flashcards:[['¿Qué mide la escala de Mohs?','La dureza relativa de los minerales (1 a 10).']] },
      { n:'Ciclo de las rocas',
        def:'Proceso cíclico por el que las rocas se transforman entre ígneas, sedimentarias y metamórficas.',
        exp:'Ígneas (enfriamiento de magma), sedimentarias (compactación de sedimentos) y metamórficas (presión/temperatura). El ciclo las interconvierte.',
        clave:['Ígnea','Sedimentaria','Metamórfica'],
        cuadro:{head:['Tipo','Origen','Ejemplo'],filas:[['Ígnea','Enfriamiento de magma','Basalto, granito'],['Sedimentaria','Compactación de sedimentos','Caliza, arenisca'],['Metamórfica','Presión y temperatura','Mármol, gneis']]},
        examen:['El mármol es una roca metamórfica derivada de la caliza.'],
        flashcards:[['¿De qué roca deriva el mármol?','De la caliza (por metamorfismo).']],
        preguntas:[['El granito es una roca:',['Sedimentaria','Ígnea','Metamórfica','Orgánica'],1,'Es ígnea intrusiva.']] }
    ]},
    { nombre: 'Unidad III. Tectónica de placas', temas: [
      { n:'Deriva continental',
        def:'Hipótesis de Alfred Wegener (1912): los continentes estuvieron unidos en Pangea y se han desplazado.',
        exp:'Se apoyó en el ajuste de costas, fósiles comunes y formaciones geológicas. Careció de un mecanismo, aportado luego por la tectónica de placas.',
        clave:['Wegener','Pangea','Fósiles compartidos'],
        examen:['Wegener propuso la deriva continental y el supercontinente Pangea.'],
        flashcards:[['¿¿Quién propuso la deriva continental?','Alfred Wegener (1912).']] },
      { n:'Tectónica de placas',
        def:'Teoría que explica que la litosfera está fragmentada en placas que se mueven sobre la astenosfera.',
        exp:'El motor son las corrientes de convección del manto. Los límites pueden ser divergentes, convergentes o transformantes.',
        clave:['Placas','Convección','Límites divergentes/convergentes/transformantes'],
        cuadro:{head:['Límite','Movimiento','Rasgo'],filas:[['Divergente','Se separan','Dorsales oceánicas'],['Convergente','Chocan','Montañas, fosas'],['Transformante','Se deslizan','Fallas (San Andrés)']]},
        examen:['El motor de las placas son las corrientes de convección del manto.'],
        flashcards:[['¿Qué mueve a las placas tectónicas?','Las corrientes de convección del manto.']],
        preguntas:[['Un límite donde las placas se separan es:',['Convergente','Divergente','Transformante','Pasivo'],1,'Divergente, como las dorsales oceánicas.']],
        diagrama:{centro:'Límites de placas',ramas:['Divergente (dorsales)','Convergente (subducción)','Transformante (fallas)']} }
    ]},
    { nombre: 'Unidad IV. Vulcanismo y sismicidad', temas: [
      { n:'Volcanes',
        def:'Estructuras por las que el magma, gases y piroclastos ascienden desde el interior a la superficie.',
        exp:'Su tipo depende de la viscosidad del magma: efusivos (lava fluida) o explosivos (magma viscoso, rico en sílice y gases).',
        clave:['Magma','Lava','Efusivo/explosivo','Piroclastos'],
        ejemplos:['El Popocatépetl, volcán activo del centro de México.'],
        examen:['Magma más viscoso (silceo) → erupciones más explosivas.'],
        flashcards:[['¿Qué hace que un volcán sea explosivo?','Un magma viscoso y rico en sílice y gases.']] },
      { n:'Sismos',
        def:'Liberación súbita de energía en la corteza que genera ondas sísmicas; suelen originarse en fallas.',
        exp:'El foco (hipocentro) es el origen; el epicentro, su proyección en superficie. Se miden por magnitud (Richter) e intensidad (Mercalli).',
        clave:['Foco/epicentro','Ondas sísmicas','Richter/Mercalli','Falla'],
        examen:['Magnitud (energía) ≠ intensidad (daños percibidos).'],
        flashcards:[['¿Diferencia entre epicentro e hipocentro?','El hipocentro es el origen interno; el epicentro, su punto en superficie.']],
        preguntas:[['La escala de Richter mide:',['Los daños','La magnitud (energía liberada)','La profundidad','La duración'],1,'Mide la magnitud o energía del sismo.']] }
    ]},
    { nombre: 'Unidad V. Intemperismo y erosión', temas: [
      { n:'Intemperismo',
        def:'Alteración y desintegración de rocas en el lugar por agentes físicos, químicos y biológicos.',
        exp:'Físico (fragmentación por hielo/calor), químico (disolución, oxidación) y biológico (raíces, líquenes). Prepara el material para la erosión.',
        clave:['Físico','Químico','Biológico','In situ'],
        examen:['Intemperismo = alteración en el sitio; erosión = transporte.'],
        flashcards:[['¿Diferencia intemperismo vs erosión?','El intemperismo altera la roca in situ; la erosión la transporta.']] },
      { n:'Erosión y suelos',
        def:'La erosión transporta los materiales alterados; el suelo es la capa superficial que sostiene la vida terrestre.',
        exp:'Agua, viento y hielo son agentes erosivos. El suelo se forma por intemperismo + materia orgánica y se organiza en horizontes (O, A, B, C).',
        clave:['Agentes: agua/viento/hielo','Horizontes','Materia orgánica'],
        cuadro:{head:['Horizonte','Contenido'],filas:[['O','Materia orgánica'],['A','Suelo fértil (humus)'],['B','Acumulación de minerales'],['C','Roca alterada']]},
        examen:['El horizonte A es el más fértil (rico en humus).'],
        flashcards:[['¿Cuál es el horizonte más fértil del suelo?','El horizonte A (rico en humus).']] }
    ]},
    { nombre: 'Unidad VI. Tiempo geológico', temas: [
      { n:'Tiempo geológico',
        def:'Escala que ordena la historia de la Tierra en eones, eras, periodos y épocas.',
        exp:'Se basa en principios como la superposición de estratos y el uso de fósiles guía. El registro cubre ~4 600 M.a.',
        clave:['Eones/eras/periodos','Superposición','Fósiles guía'],
        cuadro:{head:['Era','Vida característica'],filas:[['Paleozoica','Invertebrados, primeros vertebrados'],['Mesozoica','Dinosaurios'],['Cenozoica','Mamferos y humanos']]},
        examen:['Principio de superposición: los estratos inferiores son más antiguos.'],
        flashcards:[['¿En qué era dominaron los dinosaurios?','En la era Mesozoica.']],
        preguntas:[['Según la superposición, un estrato inferior es:',['Más joven','Más antiguo','De la misma edad','Imposible de datar'],1,'Los estratos inferiores son más antiguos.']] },
      { n:'Datación y fósiles',
        def:'Métodos para asignar edades: datación relativa (posición) y absoluta (istopos radiactivos).',
        exp:'La datación radiométrica usa la vida media de istopos (p. ej. carbono-14, uranio-plomo). Los fósiles registran la evolución de la vida.',
        clave:['Datación relativa/absoluta','Vida media','Carbono-14'],
        examen:['El carbono-14 sirve para materiales de hasta ~50 000 años.'],
        flashcards:[['¿Qué principio usa la datación radiométrica?','La vida media (desintegración) de istopos radiactivos.']] }
    ]},
    { nombre: 'Unidad VII. Atmósfera y clima', temas: [
      { n:'Atmósfera',
        def:'Capa gaseosa que envuelve la Tierra; protege la vida y regula la temperatura.',
        exp:'Se divide en tropósfera, estratósfera (con la capa de ozono), mesosfera y termósfera. El N₂ y el O₂ son sus gases principales.',
        clave:['Tropósfera','Estratsfera/ozono','N₂ y O₂'],
        examen:['La capa de ozono, en la estratósfera, filtra la radiación UV.'],
        flashcards:[['¿En qué capa está el ozono protector?','En la estratósfera.']] },
      { n:'Clima y cambio climático',
        def:'El clima es el promedio de condiciones atmosféricas a largo plazo; el cambio climático es su alteración global actual.',
        exp:'El efecto invernadero natural mantiene la temperatura habitable; el exceso de CO₂ y metano por actividad humana lo intensifica.',
        clave:['Efecto invernadero','CO₂/metano','Calentamiento global'],
        examen:['El efecto invernadero es natural; su intensificación por gases es antropogénica.'],
        flashcards:[['¿Diferencia entre tiempo y clima?','El tiempo es el estado momentneo; el clima, el promedio a largo plazo.']],
        preguntas:[['Un gas de efecto invernadero clave es:',['Nitrógeno','Dióxido de carbono','Argón','Neón'],1,'El CO₂ es un gas de efecto invernadero principal.']] }
    ]},
    { nombre: 'Unidad VIII. Hidrosfera', temas: [
      { n:'Ciclo del agua',
        def:'Circulación continua del agua entre océanos, atmósfera y continentes.',
        exp:'Procesos: evaporación, condensación, precipitación, infiltración y escorrentía. El Sol es su motor.',
        clave:['Evaporación','Condensación','Precipitación','Escorrentía'],
        examen:['El motor del ciclo del agua es la energía solar.'],
        flashcards:[['¿¿Qué energía impulsa el ciclo del agua?','La energía solar.']],
        diagrama:{centro:'Ciclo del agua',ramas:['Evaporación','Condensación','Precipitación','Infiltración','Escorrentía']} },
      { n:'Océanos y aguas continentales',
        def:'La hidrosfera incluye océanos (97% del agua) y aguas continentales (ríos, lagos, glaciares y aguas subterráneas).',
        exp:'Las corrientes oceánicas regulan el clima global. El agua dulce accesible es muy escasa (<1%).',
        clave:['Océanos 97%','Agua dulce escasa','Corrientes'],
        examen:['~97% del agua es salada; el agua dulce líquida accesible es <1%.'],
        flashcards:[['¿¿Qué porcentaje del agua es salada?','Alrededor del 97%.']] }
    ]},
    { nombre: 'Unidad IX. Geología de México', temas: [
      { n:'Geología de México',
        def:'México se ubica en el encuentro de varias placas, lo que explica su vulcanismo y sismicidad.',
        exp:'La subducción de la placa de Cocos bajo Norteamérica origina el Eje Neovolcánico Transmexicano y sismos frecuentes en el Pacífico.',
        clave:['Placa de Cocos','Eje Neovolcánico','Subducción'],
        ejemplos:['El Eje Neovolcánico atraviesa el centro del país (Popocatépetl, Nevado de Toluca).'],
        examen:['La subducción de la placa de Cocos causa gran parte de la sismicidad de México.'],
        flashcards:[['¿Qué placa subduce frente al Pacífico mexicano?','La placa de Cocos.']] }
    ]},
    { nombre: 'Unidad X. Recursos naturales y ambiente', temas: [
      { n:'Recursos geológicos',
        def:'Materiales de la corteza útiles para la sociedad: minerales metálicos, combustibles fósiles y agua.',
        exp:'Se clasifican en renovables y no renovables. Su extracción genera impactos ambientales que requieren manejo sostenible.',
        clave:['Renovable/no renovable','Minerales','Combustibles fósiles'],
        examen:['Los combustibles fósiles son recursos NO renovables.'],
        flashcards:[['¿Los combustibles fósiles son renovables?','No; se forman en escalas de tiempo geológicas.']] },
      { n:'La Tierra como sistema',
        def:'Enfoque que integra geosfera, hidrosfera, atmósfera y biosfera como subsistemas que interactúan.',
        exp:'Los ciclos biogeoquímicos (carbono, nitrógeno, agua) conectan la vida con la geología. La actividad humana altera estos ciclos.',
        clave:['Geosfera/hidrosfera/atmósfera/biosfera','Ciclos biogeoquímicos'],
        examen:['Los cuatro subsistemas terrestres interactúan mediante ciclos biogeoquímicos.'],
        flashcards:[['¿Cuáles son los subsistemas de la Tierra?','Geosfera, hidrosfera, atmósfera y biosfera.']],
        diagrama:{centro:'La Tierra como sistema',ramas:['Geosfera','Hidrosfera','Atmósfera','Biosfera']} }
    ]}
  ]
};

