// ===== Biolunet — Temario oficial (contenido didáctico) =====
// Estructura: Materia → Unidad → Tema → {def, exp, clave, ejemplos, cuadro, examen, diagrama, caso, flashcards, preguntas}
const CONTENIDO = {};
const ORDER = ['bioestadistica','hongos','plantas','molecular','tierra'];

// ============================================================
// 1) BIOESTADÍSTICA
// ============================================================
CONTENIDO.bioestadistica = {
  nombre: 'Bioestadística', icono: '📊',
  intro: 'La biología genera datos por todas partes; la estadística es el lenguaje que los convierte en conocimiento. Aquí aprenderás a describir, inferir y decidir con evidencia.',
  unidades: [
    { nombre: 'Unidad I. Introducción a la Estadística', temas: [
      { n:'Concepto de estadística',
        def:'La estadística es la ciencia que se ocupa de recolectar, organizar, describir, analizar e interpretar datos para tomar decisiones bajo incertidumbre.',
        exp:'En biología permite pasar de observaciones aisladas a conclusiones generalizables. Se divide en descriptiva (resume datos) e inferencial (generaliza a la población a partir de muestras).',
        clave:['Dato','Variable','Descriptiva','Inferencial'],
        ejemplos:['Estimar la altura promedio de una población de pinos a partir de 40 árboles medidos.'],
        examen:['La estadística descriptiva NO generaliza; solo la inferencial lo hace.'],
        flashcards:[['¿Qué dos ramas tiene la estadística?','Descriptiva (resume) e inferencial (generaliza).']],
        preguntas:[['La rama que generaliza de la muestra a la población es la:',['Descriptiva','Inferencial','Deductiva','Nominal'],1,'La inferencial usa muestras para concluir sobre poblaciones.']] },
      { n:'Error, precisión y exactitud',
        def:'Exactitud es la cercanía de una medida al valor real; precisión es la reproducibilidad entre medidas repetidas; el error es la diferencia entre lo medido y lo verdadero.',
        exp:'Una medición puede ser precisa pero inexacta (siempre se equivoca igual) o exacta pero imprecisa. Los errores pueden ser sistemáticos (sesgo) o aleatorios (azar).',
        clave:['Exactitud','Precisión','Error sistemático','Error aleatorio'],
        cuadro:{titulo:'Precisión vs. exactitud',head:['Concepto','Significado','Tipo de error asociado'],filas:[['Exactitud','Cercanía al valor real','Sistemático (sesgo)'],['Precisión','Consistencia entre repeticiones','Aleatorio']]},
        examen:['Exactitud ≠ precisión: recuerda la analogía de la diana.'],
        flashcards:[['¿Diferencia entre exactitud y precisión?','Exactitud = cerca del valor real; precisión = medidas consistentes entre sí.']] },
      { n:'Poblaciones y muestras',
        def:'Población es el conjunto total de individuos u observaciones de interés; muestra es un subconjunto representativo de esa población.',
        exp:'Como rara vez podemos medir toda la población, tomamos muestras. Una buena muestra debe ser representativa y del tamaño adecuado para inferir con validez.',
        clave:['Población','Muestra','Representatividad','Censo'],
        ejemplos:['Población: todos los axolotes de Xochimilco. Muestra: 120 axolotes capturados y liberados.'],
        flashcards:[['¿Qué es una muestra?','Subconjunto representativo de la población de estudio.']] },
      { n:'Criterios de inclusión, exclusión y eliminación',
        def:'Reglas que definen quién entra al estudio (inclusión), quién no puede entrar (exclusión) y quién sale una vez iniciado (eliminación).',
        exp:'Garantizan que la muestra sea homogénea y válida. Inclusión y exclusión se aplican ANTES de iniciar; la eliminación ocurre DURANTE el estudio (p. ej. abandono).',
        clave:['Inclusión','Exclusión','Eliminación'],
        cuadro:{head:['Criterio','Momento','Ejemplo'],filas:[['Inclusión','Antes','Ratones machos de 8 semanas'],['Exclusión','Antes','Con enfermedad previa'],['Eliminación','Durante','Muere o abandona el estudio']]},
        examen:['Exclusión = antes de entrar; eliminación = después de haber entrado.'],
        flashcards:[['¿Cuándo se aplica la eliminación?','Durante el estudio, cuando un sujeto ya incluido debe retirarse.']] },
      { n:'Tipos de estudios',
        def:'Clasificación de los diseños de investigación según el tiempo, la intervención y el objetivo.',
        exp:'Se combinan varios ejes: temporalidad (longitudinal/transversal), dirección (retrospectivo/prospectivo), objetivo (descriptivo/comparativo) y control (observacional/experimental).',
        clave:['Longitudinal','Transversal','Descriptivo','Comparativo','Observacional','Experimental','Retrospectivo','Prospectivo'],
        cuadro:{titulo:'Ejes de clasificación de estudios',head:['Eje','Opción A','Opción B'],filas:[['Tiempo','Longitudinal (varios momentos)','Transversal (un momento)'],['Objetivo','Descriptivo (describe)','Comparativo (compara grupos)'],['Intervención','Observacional (solo observa)','Experimental (manipula)'],['Dirección','Retrospectivo (hacia el pasado)','Prospectivo (hacia el futuro)']]},
        ejemplos:['Longitudinal: seguir el crecimiento de larvas cada semana durante 3 meses.','Transversal: medir el peso de todas las larvas en un solo día.'],
        examen:['Transversal = una foto en el tiempo; longitudinal = seguimiento.','Experimental implica manipular una variable; observacional no.'],
        flashcards:[['¿Diferencia longitudinal vs transversal?','Longitudinal mide en varios momentos; transversal en un solo momento.'],['¿Qué distingue a un estudio experimental?','El investigador manipula la variable independiente.']],
        preguntas:[['Un estudio que mide una variable en un solo momento es:',['Longitudinal','Transversal','Prospectivo','Experimental'],1,'Transversal = una sola medición en el tiempo.']] },
      { n:'Protocolos de investigación',
        def:'Diseños concretos para recolectar evidencia: encuestas, estudios de caso, casos y controles, cohortes y estudios experimentales.',
        exp:'La encuesta recoge datos de una muestra; el estudio de caso analiza a fondo pocos sujetos; casos y controles compara enfermos vs sanos hacia el pasado; cohortes sigue grupos expuestos/no expuestos hacia el futuro; el experimental asigna tratamientos.',
        clave:['Encuesta','Estudio de caso','Casos y controles','Cohorte','Experimental'],
        cuadro:{head:['Protocolo','Dirección','Compara'],filas:[['Casos y controles','Retrospectivo','Enfermos vs sanos'],['Cohorte','Prospectivo','Expuestos vs no expuestos'],['Experimental','Prospectivo','Tratamiento vs control']]},
        examen:['Casos y controles = retrospectivo; cohorte = prospectivo.'],
        flashcards:[['¿Qué compara un estudio de casos y controles?','Sujetos con la enfermedad (casos) frente a sanos (controles), mirando al pasado.']] },
      { n:'Estadística descriptiva e inferencial',
        def:'La descriptiva resume y presenta los datos de la muestra; la inferencial usa esos datos para hacer estimaciones y probar hipótesis sobre la población.',
        exp:'La descriptiva emplea medidas de tendencia y dispersión y gráficas; la inferencial emplea probabilidad, intervalos de confianza y pruebas de hipótesis.',
        clave:['Resumen','Estimación','Prueba de hipótesis'],
        flashcards:[['¿Qué herramienta usa la inferencial y no la descriptiva?','La probabilidad para generalizar a la población.']] },
      { n:'Causalidad en investigación',
        def:'Relación en la que un factor (causa) produce un efecto. Correlación no implica causalidad.',
        exp:'Los criterios de Bradford Hill (fuerza, temporalidad, consistencia, gradiente dosis-respuesta, plausibilidad) ayudan a juzgar causalidad. Solo los estudios experimentales bien controlados permiten inferirla con fuerza.',
        clave:['Causa','Efecto','Correlación','Confusión','Temporalidad'],
        examen:['“Correlación no implica causalidad”: frase clave de examen.'],
        flashcards:[['¿La correlación implica causalidad?','No; puede haber variables de confusión o azar.']],
        preguntas:[['Para establecer causalidad de forma sólida se prefiere un estudio:',['Transversal','Observacional','Experimental controlado','De caso'],2,'El experimento controlado permite aislar la causa.']] }
    ]},
    { nombre: 'Unidad II. Estadística Descriptiva', temas: [
      { n:'Población y muestra',
        def:'Población: totalidad de elementos; muestra: parte seleccionada de ella para el análisis.',
        exp:'La descriptiva puede aplicarse tanto a poblaciones como a muestras; la notación cambia (parámetros vs estadísticos).',
        clave:['Población','Muestra','Unidad de análisis'],
        flashcards:[['¿Muestra o población: 50 células contadas de un cultivo?','Muestra.']] },
      { n:'Parámetros y estadísticos',
        def:'Parámetro es una medida que describe a la población (μ, σ); estadístico es la medida calculada en la muestra (x̄, s).',
        exp:'Usamos estadísticos muestrales para estimar parámetros poblacionales desconocidos.',
        clave:['Parámetro (μ,σ)','Estadístico (x̄,s)','Estimación'],
        cuadro:{head:['Medida','Población','Muestra'],filas:[['Media','μ','x̄'],['Desv. estándar','σ','s'],['Tamaño','N','n']]},
        examen:['μ y σ = población; x̄ y s = muestra.'],
        flashcards:[['¿Qué símbolo representa la media poblacional?','μ (mu).']] },
      { n:'Variables y escalas de medición',
        def:'Variable es una característica que varía entre individuos. Las escalas son: nominal, ordinal, de intervalo y de razón.',
        exp:'Nominal (categorías sin orden), ordinal (categorías ordenadas), intervalo (sin cero absoluto, p. ej. °C) y razón (con cero absoluto, p. ej. peso).',
        clave:['Nominal','Ordinal','Intervalo','Razón','Cualitativa','Cuantitativa'],
        cuadro:{titulo:'Escalas de medición',head:['Escala','¿Orden?','¿Cero absoluto?','Ejemplo'],filas:[['Nominal','No','No','Especie'],['Ordinal','Sí','No','Grado de infección'],['Intervalo','Sí','No','Temperatura °C'],['Razón','Sí','Sí','Masa (g)']]},
        examen:['La escala de razón es la única con cero absoluto verdadero.'],
        flashcards:[['¿Qué escala tiene cero absoluto?','La de razón (p. ej. peso, longitud).']],
        preguntas:[['La temperatura en °C corresponde a una escala:',['Nominal','Ordinal','De intervalo','De razón'],2,'No tiene cero absoluto: 0°C no es ausencia de temperatura.']] },
      { n:'Barras',
        def:'Gráfica de barras: representa frecuencias de variables cualitativas o discretas con rectángulos separados.',
        exp:'La altura de cada barra es proporcional a la frecuencia. Las barras van separadas (a diferencia del histograma).',
        clave:['Frecuencia','Cualitativa','Barras separadas'],
        flashcards:[['¿Barras separadas o juntas?','Separadas; el histograma las lleva juntas.']] },
      { n:'Pictogramas',
        def:'Gráfica que usa íconos o imágenes para representar cantidades.',
        exp:'Cada símbolo equivale a un número de unidades; útil para divulgación, poco preciso para análisis.',
        clave:['Íconos','Divulgación'],
        flashcards:[['¿Qué representa cada símbolo en un pictograma?','Una cantidad fija de unidades.']] },
      { n:'Gráficas circulares',
        def:'Gráfica de pastel: muestra proporciones de un total como sectores de un círculo.',
        exp:'Cada sector es proporcional al porcentaje; ideal para composición (partes de un todo).',
        clave:['Proporción','Porcentaje','Sectores'],
        flashcards:[['¿Cuándo conviene una gráfica circular?','Para mostrar la composición porcentual de un total.']] },
      { n:'Histogramas',
        def:'Gráfica de barras contiguas que representa la distribución de una variable cuantitativa continua agrupada en intervalos.',
        exp:'Permite ver forma, centro y dispersión de la distribución (simétrica, sesgada, etc.). Las barras se tocan porque los intervalos son continuos.',
        clave:['Intervalos de clase','Continua','Distribución'],
        examen:['Histograma = variable continua, barras juntas.'],
        flashcards:[['¿Qué tipo de variable grafica un histograma?','Cuantitativa continua.']] },
      { n:'Diagramas de caja',
        def:'Boxplot: resume una distribución con mínimo, Q1, mediana, Q3 y máximo, mostrando dispersión y valores atípicos.',
        exp:'La caja abarca el rango intercuartílico (Q1–Q3); la línea interna es la mediana; los bigotes llegan a los extremos no atípicos.',
        clave:['Cuartiles','Mediana','Rango intercuartílico','Atípicos'],
        examen:['El interior de la caja = 50% central de los datos (RIC).'],
        flashcards:[['¿Qué muestra la línea dentro de la caja?','La mediana (Q2).']] },
      { n:'Diagramas de tallo y hoja',
        def:'Representación que separa cada dato en tallo (dígitos mayores) y hoja (dígito menor), conservando los valores originales.',
        exp:'Combina tabla y gráfica: muestra la forma de la distribución sin perder los datos exactos.',
        clave:['Tallo','Hoja','Distribución'],
        flashcards:[['Ventaja del tallo y hoja','Conserva los valores originales mientras muestra la distribución.']] },
      { n:'Polígono de frecuencias',
        def:'Línea que une los puntos medios de las clases de un histograma para mostrar la distribución.',
        exp:'Útil para comparar dos o más distribuciones en el mismo gráfico.',
        clave:['Punto medio','Frecuencia'],
        flashcards:[['¿Qué une un polígono de frecuencias?','Los puntos medios de las clases.']] },
      { n:'Diagramas X-Y',
        def:'Diagrama de dispersión: representa pares de valores de dos variables cuantitativas para explorar su relación.',
        exp:'Permite ver correlación (positiva, negativa o nula) y tendencia entre X e Y.',
        clave:['Dispersión','Correlación','Tendencia'],
        ejemplos:['Relación entre temperatura y tasa de respiración en insectos.'],
        flashcards:[['¿Para qué sirve un diagrama X-Y?','Para explorar la relación entre dos variables cuantitativas.']] },
      { n:'Media',
        def:'Promedio aritmético: suma de los valores dividida entre el número de datos.',
        exp:'Es sensible a valores extremos (atípicos). Se usa con datos de intervalo o razón aproximadamente simétricos.',
        clave:['Promedio','Tendencia central','Sensible a atípicos'],
        examen:['La media se ve muy afectada por valores extremos.'],
        flashcards:[['¿Cómo se calcula la media?','Sumando todos los datos y dividiendo entre n.']] },
      { n:'Mediana',
        def:'Valor que ocupa la posición central cuando los datos se ordenan; deja 50% por debajo y 50% por encima.',
        exp:'Es robusta frente a valores atípicos, por eso se prefiere en distribuciones sesgadas.',
        clave:['Posición central','Robusta','Percentil 50'],
        examen:['Con datos sesgados o atípicos, reporta mediana en vez de media.'],
        flashcards:[['¿Qué medida es robusta ante atípicos?','La mediana.']] },
      { n:'Moda',
        def:'Valor que se repite con mayor frecuencia en el conjunto de datos.',
        exp:'Es la única medida de tendencia central aplicable a variables nominales. Puede no existir o haber varias (bimodal).',
        clave:['Frecuencia máxima','Nominal','Bimodal'],
        flashcards:[['¿Única medida válida para datos nominales?','La moda.']] },
      { n:'Rango',
        def:'Medida de dispersión: diferencia entre el valor máximo y el mínimo.',
        exp:'Es simple pero muy sensible a valores extremos y no considera la distribución interna.',
        clave:['Dispersión','Máx − Mín'],
        flashcards:[['¿Cómo se obtiene el rango?','Valor máximo menos valor mínimo.']] },
      { n:'Varianza',
        def:'Promedio de los cuadrados de las desviaciones respecto a la media; mide la dispersión.',
        exp:'Al elevar al cuadrado, sus unidades quedan al cuadrado; por eso suele reportarse su raíz (desviación estándar).',
        clave:['Dispersión','Desviaciones al cuadrado','s² / σ²'],
        flashcards:[['¿Relación entre varianza y desviación estándar?','La desviación estándar es la raíz cuadrada de la varianza.']] },
      { n:'Desviación estándar',
        def:'Raíz cuadrada de la varianza; expresa la dispersión en las mismas unidades que los datos.',
        exp:'Cuanto mayor es, más dispersos están los datos alrededor de la media.',
        clave:['Dispersión','Mismas unidades','s / σ'],
        examen:['La desviación estándar tiene las mismas unidades que los datos; la varianza no.'],
        flashcards:[['¿Ventaja de la desviación estándar sobre la varianza?','Conserva las unidades originales.']],
        preguntas:[['¿Qué medida NO cambia sus unidades respecto a los datos?',['Varianza','Desviación estándar','Varianza al cuadrado','Ninguna'],1,'La desviación estándar conserva las unidades.']] },
      { n:'Regla empírica',
        def:'En una distribución normal, ~68% de los datos caen dentro de ±1σ, ~95% dentro de ±2σ y ~99.7% dentro de ±3σ.',
        exp:'Permite estimar rápidamente qué proporción de datos se aleja de la media en datos aproximadamente normales.',
        clave:['68-95-99.7','Normal','Desviaciones'],
        examen:['Memoriza 68 – 95 – 99.7 para ±1, ±2 y ±3 σ.'],
        flashcards:[['¿Qué % cae dentro de ±2σ (regla empírica)?','Aproximadamente 95%.']] },
      { n:'Teorema de Tchebyshev',
        def:'Para cualquier distribución, al menos (1−1/k²) de los datos cae dentro de k desviaciones estándar de la media (k>1).',
        exp:'A diferencia de la regla empírica, aplica a cualquier forma de distribución. Para k=2 garantiza al menos 75%; para k=3, al menos 88.9%.',
        clave:['1−1/k²','Cualquier distribución','Cota mínima'],
        examen:['Tchebyshev sirve para CUALQUIER distribución; la regla empírica solo para la normal.'],
        flashcards:[['Con k=2, ¿qué garantiza Tchebyshev?','Al menos 75% de los datos dentro de ±2σ.']] }
    ]},
    { nombre: 'Unidad III. Probabilidad', temas: [
      { n:'Fenómenos deterministas y estocásticos',
        def:'Deterministas: su resultado está completamente predeterminado por las condiciones. Estocásticos (aleatorios): su resultado depende del azar.',
        exp:'La probabilidad estudia los fenómenos estocásticos, donde no podemos predecir el resultado exacto pero sí su comportamiento a largo plazo.',
        clave:['Determinista','Estocástico','Azar'],
        flashcards:[['¿Qué fenómenos estudia la probabilidad?','Los estocásticos (aleatorios).']] },
      { n:'Espacio muestral y eventos',
        def:'Espacio muestral (S) es el conjunto de todos los resultados posibles; un evento es cualquier subconjunto de S.',
        exp:'Un evento simple tiene un solo resultado; uno compuesto, varios. La probabilidad de un evento va de 0 a 1.',
        clave:['Espacio muestral S','Evento','Resultado'],
        ejemplos:['Al cruzar Aa×Aa, S={AA,Aa,aA,aa}; evento “recesivo”={aa}.'],
        flashcards:[['¿Qué es el espacio muestral?','El conjunto de todos los resultados posibles de un experimento.']] },
      { n:'Combinaciones y ordenaciones',
        def:'Ordenaciones (permutaciones) cuentan arreglos donde el orden importa; combinaciones cuentan selecciones donde el orden no importa.',
        exp:'Permutaciones: nPr = n!/(n−r)!. Combinaciones: nCr = n!/[r!(n−r)!]. Se usan para calcular espacios muestrales.',
        clave:['Permutación','Combinación','Factorial'],
        cuadro:{head:['Concepto','¿Importa el orden?','Fórmula'],filas:[['Permutación','Sí','n!/(n−r)!'],['Combinación','No','n!/[r!(n−r)!]']]},
        examen:['Si el orden importa → permutación; si no → combinación.'],
        flashcards:[['¿Combinación o permutación si el orden importa?','Permutación.']] },
      { n:'Probabilidad clásica y frecuentista',
        def:'Clásica: casos favorables/casos posibles (a priori). Frecuentista: frecuencia relativa observada al repetir el experimento muchas veces (a posteriori).',
        exp:'La clásica supone resultados equiprobables; la frecuentista se basa en la observación empírica.',
        clave:['Clásica','Frecuentista','Frecuencia relativa'],
        flashcards:[['¿Fórmula de la probabilidad clásica?','Casos favorables / casos posibles.']] },
      { n:'Ley de la adición',
        def:'P(A∪B) = P(A) + P(B) − P(A∩B). Para eventos mutuamente excluyentes, P(A∪B)=P(A)+P(B).',
        exp:'Se usa para la probabilidad de que ocurra A O B.',
        clave:['Unión','Mutuamente excluyentes'],
        examen:['Si A y B son excluyentes, P(A∩B)=0.'],
        flashcards:[['¿Ley de la adición general?','P(A∪B)=P(A)+P(B)−P(A∩B).']] },
      { n:'Ley de la multiplicación',
        def:'P(A∩B)=P(A)·P(B|A). Para eventos independientes, P(A∩B)=P(A)·P(B).',
        exp:'Se usa para la probabilidad de que ocurran A Y B.',
        clave:['Intersección','Independencia','Condicional'],
        flashcards:[['¿Probabilidad de A y B si son independientes?','P(A)·P(B).']] },
      { n:'Teorema de Bayes',
        def:'Permite actualizar la probabilidad de una hipótesis dada nueva evidencia: P(A|B)=P(B|A)P(A)/P(B).',
        exp:'Es fundamental en diagnóstico: relaciona sensibilidad, prevalencia y valor predictivo de una prueba.',
        clave:['Probabilidad condicional','A posteriori','Diagnóstico'],
        ejemplos:['Calcular la probabilidad real de estar enfermo dado un test positivo, considerando la prevalencia.'],
        examen:['Bayes conecta P(A|B) con P(B|A) mediante las probabilidades previas.'],
        flashcards:[['¿Para qué sirve el teorema de Bayes?','Para actualizar probabilidades al incorporar nueva evidencia.']] },
      { n:'Variables aleatorias',
        def:'Función que asigna un valor numérico a cada resultado del espacio muestral. Pueden ser discretas o continuas.',
        exp:'Las discretas toman valores contables (número de crías); las continuas, cualquier valor en un intervalo (peso).',
        clave:['Discreta','Continua','Distribución'],
        flashcards:[['¿Variable discreta o continua: número de huevos?','Discreta.']] },
      { n:'Binomial',
        def:'Distribución discreta que modela el número de éxitos en n ensayos independientes con probabilidad p constante.',
        exp:'Requiere: número fijo de ensayos, dos resultados (éxito/fracaso), p constante e independencia.',
        clave:['Éxito/fracaso','n ensayos','p constante'],
        ejemplos:['Probabilidad de obtener 3 descendientes recesivos de 5 en un cruce Aa×Aa.'],
        examen:['Binomial: dos resultados, n fijo, p constante, ensayos independientes.'],
        flashcards:[['¿Qué modela la distribución binomial?','El número de éxitos en n ensayos independientes.']] },
      { n:'Poisson',
        def:'Distribución discreta que modela el número de eventos raros en un intervalo fijo de tiempo o espacio.',
        exp:'Depende de un solo parámetro λ (media = varianza). Útil cuando los eventos son independientes y poco frecuentes.',
        clave:['Eventos raros','λ','media = varianza'],
        ejemplos:['Número de colonias bacterianas por placa; mutaciones por gen por generación.'],
        examen:['En Poisson, media = varianza = λ.'],
        flashcards:[['¿Qué modela Poisson?','Eventos raros en un intervalo fijo (λ = media = varianza).']] },
      { n:'Binomial negativa',
        def:'Distribución discreta que modela el número de ensayos necesarios hasta obtener un número fijo de éxitos.',
        exp:'También se usa para datos de conteo sobredispersos (varianza > media), comunes en ecología.',
        clave:['Ensayos hasta éxito','Sobredispersión'],
        flashcards:[['¿Cuándo usar binomial negativa en ecología?','Con datos de conteo sobredispersos (varianza > media).']] },
      { n:'Normal',
        def:'Distribución continua simétrica en forma de campana, definida por su media μ y desviación estándar σ.',
        exp:'Muchas variables biológicas (talla, peso) la siguen aproximadamente. Es la base de gran parte de la inferencia.',
        clave:['Campana','Simétrica','μ y σ'],
        examen:['En la normal, media = mediana = moda.'],
        flashcards:[['¿Qué dos parámetros definen la normal?','La media μ y la desviación estándar σ.']] },
      { n:'Normal estándar',
        def:'Distribución normal con media 0 y desviación estándar 1; sus valores se llaman puntuaciones Z.',
        exp:'Cualquier normal se estandariza con Z=(x−μ)/σ, permitiendo usar tablas Z.',
        clave:['Z','μ=0, σ=1','Estandarización'],
        examen:['Fórmula clave: Z = (x − μ)/σ.'],
        flashcards:[['¿Cómo se calcula una puntuación Z?','Z = (x − μ)/σ.']],
        preguntas:[['La normal estándar tiene:',['μ=1, σ=0','μ=0, σ=1','μ=0, σ=0','μ=1, σ=1'],1,'Media 0 y desviación estándar 1.']] },
      { n:'t de Student',
        def:'Distribución similar a la normal pero con colas más pesadas, usada con muestras pequeñas y σ desconocida.',
        exp:'Depende de los grados de libertad; al aumentar n se aproxima a la normal. Base de la prueba t.',
        clave:['Muestras pequeñas','Grados de libertad','σ desconocida'],
        examen:['Usa t cuando n es pequeño y no conoces σ.'],
        flashcards:[['¿Cuándo se usa la t de Student?','Con muestras pequeñas y varianza poblacional desconocida.']] },
      { n:'F de Fisher',
        def:'Distribución del cociente de dos varianzas; base del análisis de varianza (ANOVA).',
        exp:'Se usa para comparar varianzas o medias de varios grupos simultáneamente.',
        clave:['Cociente de varianzas','ANOVA'],
        flashcards:[['¿En qué prueba se usa la F de Fisher?','En el ANOVA (comparación de varianzas/medias).']] },
      { n:'Ji cuadrada',
        def:'Distribución usada para variables categóricas: pruebas de bondad de ajuste e independencia.',
        exp:'Compara frecuencias observadas con esperadas. Solo toma valores positivos y depende de los grados de libertad.',
        clave:['Categóricas','Observado vs esperado','χ²'],
        ejemplos:['Comprobar si las proporciones de un cruce genético se ajustan a 9:3:3:1.'],
        examen:['Ji cuadrada compara frecuencias observadas vs esperadas.'],
        flashcards:[['¿Qué compara la prueba ji cuadrada?','Frecuencias observadas frente a esperadas en datos categóricos.']] }
    ]},
    { nombre: 'Unidad IV. Distribuciones Muestrales', temas: [
      { n:'Conceptos básicos de muestreo',
        def:'El muestreo es el proceso de seleccionar una parte de la población para estudiarla; busca representatividad y minimizar sesgos.',
        exp:'Un buen muestreo garantiza que las conclusiones puedan generalizarse a la población.',
        clave:['Representatividad','Sesgo','Marco muestral'],
        flashcards:[['Objetivo del muestreo','Obtener una muestra representativa para generalizar a la población.']] },
      { n:'Tipos de muestreo',
        def:'Probabilístico (aleatorio simple, sistemático, estratificado, por conglomerados) y no probabilístico (por conveniencia, por cuotas).',
        exp:'Solo el probabilístico permite calcular el error de muestreo y hacer inferencia válida.',
        clave:['Aleatorio simple','Estratificado','Conglomerados','No probabilístico'],
        cuadro:{head:['Tipo','Selección','¿Inferencia válida?'],filas:[['Probabilístico','Al azar conocido','Sí'],['No probabilístico','Subjetiva/conveniencia','Limitada']]},
        examen:['Solo el muestreo probabilístico permite inferencia estadística formal.'],
        flashcards:[['¿Qué muestreo divide en subgrupos homogéneos?','El estratificado.']] },
      { n:'Distribuciones muestrales',
        def:'Distribución de probabilidad de un estadístico (p. ej. la media) calculado en todas las muestras posibles de tamaño n.',
        exp:'Es el puente entre la muestra y la población: describe cuánto varía un estadístico entre muestras.',
        clave:['Estadístico','Variabilidad muestral','Error estándar'],
        flashcards:[['¿Qué describe una distribución muestral?','Cómo varía un estadístico entre todas las muestras posibles.']] },
      { n:'Distribución de la media muestral',
        def:'Distribución de las medias de todas las muestras posibles; su media es μ y su error estándar es σ/√n.',
        exp:'A mayor tamaño de muestra, menor error estándar y estimación más precisa.',
        clave:['Error estándar σ/√n','Precisión'],
        examen:['El error estándar de la media disminuye con √n.'],
        flashcards:[['¿Error estándar de la media?','σ/√n.']] },
      { n:'Teorema Central del Límite',
        def:'La distribución de la media muestral se aproxima a una normal cuando n es grande, sin importar la forma de la población.',
        exp:'Suele considerarse suficiente n≥30. Es la base que justifica el uso de la normal en inferencia.',
        clave:['n≥30','Aproximación normal','Fundamento de la inferencia'],
        examen:['El TCL funciona aunque la población no sea normal, si n es grande.'],
        flashcards:[['¿Qué afirma el Teorema Central del Límite?','La media muestral tiende a distribuirse normalmente al crecer n.']],
        preguntas:[['Según el TCL, la media muestral tiende a una distribución:',['Uniforme','Normal','Binomial','Exponencial'],1,'Se aproxima a la normal al aumentar n.']] },
      { n:'Distribución de proporciones muestrales',
        def:'Distribución de las proporciones (p̂) calculadas en muestras; su media es p y su error estándar √[p(1−p)/n].',
        exp:'Permite inferir proporciones poblacionales (p. ej. frecuencia de un alelo).',
        clave:['Proporción p̂','Error estándar de proporción'],
        flashcards:[['¿Error estándar de una proporción?','√[p(1−p)/n].']] }
    ]},
    { nombre: 'Unidad V. Inferencia Estadística', temas: [
      { n:'Inferencia estadística',
        def:'Proceso de sacar conclusiones sobre una población a partir de una muestra, mediante estimación y pruebas de hipótesis.',
        exp:'Incluye estimación puntual, intervalos de confianza y contraste de hipótesis.',
        clave:['Estimación','Hipótesis','Generalización'],
        flashcards:[['Objetivo de la inferencia','Concluir sobre la población usando datos de una muestra.']] },
      { n:'Estadística paramétrica',
        def:'Pruebas que asumen que los datos siguen una distribución conocida (normal) y trabajan con parámetros como la media.',
        exp:'Ejemplos: prueba t, ANOVA, regresión. Requieren supuestos (normalidad, homogeneidad de varianzas).',
        clave:['Supuesto de normalidad','t, ANOVA','Media'],
        cuadro:{head:['Aspecto','Paramétrica','No paramétrica'],filas:[['Supuestos','Normalidad','Pocos/ninguno'],['Trabaja con','Media/varianza','Rangos/medianas'],['Potencia','Mayor','Menor']]},
        examen:['Paramétrica exige normalidad; no paramétrica no.'],
        flashcards:[['¿Ejemplo de prueba paramétrica?','La prueba t de Student o el ANOVA.']] },
      { n:'Estadística no paramétrica',
        def:'Pruebas que no exigen una distribución específica; trabajan con rangos y medianas.',
        exp:'Ejemplos: U de Mann-Whitney, Wilcoxon, Kruskal-Wallis. Útiles con muestras pequeñas u ordinales.',
        clave:['Sin supuesto de normalidad','Rangos','Mann-Whitney'],
        flashcards:[['¿Cuándo preferir pruebas no paramétricas?','Cuando no se cumple normalidad o los datos son ordinales.']] },
      { n:'Estadística univariada',
        def:'Análisis de una sola variable a la vez.',
        exp:'Describe o contrasta una única característica (p. ej. distribución de tallas).',
        clave:['Una variable'],
        flashcards:[['¿Univariada?','Análisis de una sola variable.']] },
      { n:'Estadística multivariada',
        def:'Análisis simultáneo de dos o más variables y sus relaciones.',
        exp:'Incluye regresión múltiple, análisis de componentes principales y de conglomerados; clave en ecología y genómica.',
        clave:['Varias variables','PCA','Regresión múltiple'],
        flashcards:[['¿Ejemplo de técnica multivariada?','Análisis de componentes principales (PCA).']] },
      { n:'Intervalos de confianza',
        def:'Rango de valores que, con cierto nivel de confianza (p. ej. 95%), contiene el parámetro poblacional.',
        exp:'Un IC del 95% significa que el 95% de los intervalos así construidos contendrían el parámetro. Su amplitud depende de n, σ y el nivel de confianza.',
        clave:['Nivel de confianza','Margen de error','Precisión'],
        examen:['Un IC más ancho = menos precisión; a mayor n, IC más estrecho.'],
        flashcards:[['¿Qué significa un IC del 95%?','El 95% de los intervalos así calculados contendrían el parámetro real.']] },
      { n:'Tamaño de muestra',
        def:'Número de unidades necesarias para detectar un efecto con la precisión y potencia deseadas.',
        exp:'Depende del error permitido, la variabilidad, el nivel de confianza y la potencia. Muestras muy pequeñas reducen la potencia.',
        clave:['Potencia','Precisión','Variabilidad'],
        flashcards:[['¿Qué pasa con una muestra muy pequeña?','Baja la potencia y aumenta el riesgo de no detectar efectos reales.']] },
      { n:'Hipótesis estadísticas',
        def:'Afirmaciones sobre la población: la nula (H₀, no hay efecto/diferencia) y la alternativa (H₁, sí lo hay).',
        exp:'La prueba busca reunir evidencia para rechazar o no H₀. Nunca se “acepta” H₀, solo no se rechaza.',
        clave:['H₀','H₁','Rechazo'],
        examen:['No se “acepta” H₀; se “no rechaza”.'],
        flashcards:[['¿Qué afirma la hipótesis nula?','Que no hay efecto o diferencia.']] },
      { n:'Error tipo I',
        def:'Rechazar H₀ cuando en realidad es verdadera (falso positivo). Su probabilidad es α.',
        exp:'El nivel de significancia α (comúnmente 0.05) fija el riesgo aceptable de error tipo I.',
        clave:['Falso positivo','α','Significancia'],
        cuadro:{head:['Decisión','H₀ verdadera','H₀ falsa'],filas:[['Rechazar H₀','Error tipo I (α)','Correcto'],['No rechazar H₀','Correcto','Error tipo II (β)']]},
        examen:['Error I = falso positivo (α); Error II = falso negativo (β).'],
        flashcards:[['¿Qué es el error tipo I?','Rechazar una H₀ verdadera (falso positivo).']],
        preguntas:[['Rechazar una hipótesis nula verdadera es un error:',['Tipo I','Tipo II','De muestreo','Sistemático'],0,'Error tipo I = falso positivo (α).']] },
      { n:'Error tipo II',
        def:'No rechazar H₀ cuando en realidad es falsa (falso negativo). Su probabilidad es β.',
        exp:'La potencia de la prueba es 1−β: la capacidad de detectar un efecto real.',
        clave:['Falso negativo','β','Potencia = 1−β'],
        flashcards:[['¿Qué es la potencia estadística?','1−β: probabilidad de detectar un efecto real.']] },
      { n:'Pruebas de hipótesis',
        def:'Procedimiento para decidir entre H₀ y H₁ usando un estadístico de prueba y un valor p.',
        exp:'Si p < α, se rechaza H₀. Pasos: plantear hipótesis, fijar α, calcular el estadístico, comparar y concluir.',
        clave:['Valor p','α','Estadístico de prueba'],
        examen:['Regla de decisión: si p < α → se rechaza H₀.'],
        flashcards:[['¿Cuándo se rechaza H₀?','Cuando el valor p es menor que α.']] },
      { n:'Ji cuadrada',
        def:'Prueba no paramétrica para datos categóricos que compara frecuencias observadas con esperadas.',
        exp:'Se aplica a bondad de ajuste, homogeneidad e independencia mediante tablas de contingencia.',
        clave:['χ²','Frecuencias','Contingencia'],
        flashcards:[['¿Tipo de datos de la ji cuadrada?','Categóricos (frecuencias).']] },
      { n:'Homogeneidad',
        def:'Prueba χ² que evala si varias poblaciones tienen la misma distribución de una variable categórica.',
        exp:'Compara si la proporción de categorías es igual entre grupos.',
        clave:['Misma distribución','Comparar grupos'],
        flashcards:[['¿Qué evala la prueba de homogeneidad?','Si varios grupos comparten la misma distribución categórica.']] },
      { n:'Asociación',
        def:'Grado en que dos variables categóricas están relacionadas.',
        exp:'La χ² detecta asociación; medidas como V de Cramér cuantifican su fuerza.',
        clave:['Relación','V de Cramér'],
        flashcards:[['¿Qué detecta la asociación χ²?','Si dos variables categóricas están relacionadas.']] },
      { n:'Independencia',
        def:'Prueba χ² que evala si dos variables categóricas son independientes entre sí.',
        exp:'H₀: las variables son independientes. Si se rechaza, existe asociación.',
        clave:['Independencia','Tabla de contingencia'],
        examen:['En la prueba de independencia, H₀ = “las variables son independientes”.'],
        flashcards:[['¿Qué afirma H₀ en la prueba de independencia?','Que las dos variables son independientes.']] },
      { n:'Bondad de ajuste',
        def:'Prueba χ² que compara una distribución observada con una teórica esperada.',
        exp:'Muy usada en genética para comprobar proporciones mendelianas (3:1, 9:3:3:1).',
        clave:['Observado vs teórico','Proporciones mendelianas'],
        ejemplos:['Verificar si un cruce dihibrido se ajusta a 9:3:3:1.'],
        flashcards:[['¿Uso clásico de la bondad de ajuste en genética?','Comprobar proporciones mendelianas esperadas.']] }
    ]},
    { nombre: 'Unidad VI. Introducción a los Modelos Estadísticos Lineales', temas: [
      { n:'Modelos estadísticos lineales',
        def:'Modelos que expresan una variable respuesta como combinación lineal de variables predictoras más un error.',
        exp:'Incluyen regresión y ANOVA. Forma general: Y = β₀ + β₁X₁ + ... + ε.',
        clave:['Variable respuesta','Predictores','Término de error'],
        flashcards:[['¿Forma general de un modelo lineal?','Y = β₀ + β₁X + ε.']] },
      { n:'Regresión',
        def:'Técnica que modela la relación entre una variable dependiente y una o más independientes para predecir o explicar.',
        exp:'La regresión lineal simple ajusta una recta (Y=a+bX); el coeficiente de determinación R² indica el ajuste.',
        clave:['Dependiente','Independiente','Recta de ajuste','R²'],
        ejemplos:['Predecir la biomasa de una planta a partir de la cantidad de luz recibida.'],
        examen:['R² cercano a 1 = buen ajuste del modelo.'],
        flashcards:[['¿Qué indica el R² en regresión?','La proporción de variabilidad explicada por el modelo.']] },
      { n:'Conceptos básicos',
        def:'Elementos de un modelo: variables, coeficientes, residuos, pendiente e intercepto.',
        exp:'El residuo es la diferencia entre el valor observado y el predicho; minimizarlos (mínimos cuadrados) da el mejor ajuste.',
        clave:['Pendiente','Intercepto','Residuo','Mínimos cuadrados'],
        flashcards:[['¿Qué es un residuo?','La diferencia entre el valor observado y el predicho por el modelo.']] },
      { n:'Supuestos',
        def:'Condiciones para validez del modelo lineal: linealidad, independencia, normalidad de residuos y homocedasticidad.',
        exp:'Si se violan, las conclusiones pueden ser inválidas; se revisan con gráficos de residuos.',
        clave:['Linealidad','Independencia','Normalidad','Homocedasticidad'],
        examen:['Homocedasticidad = varianza constante de los residuos.'],
        flashcards:[['¿Qué es la homocedasticidad?','Que la varianza de los residuos sea constante.']] },
      { n:'Aplicaciones',
        def:'Usos de los modelos lineales en biología: predicción de crecimiento, dosis-respuesta, calibración, etc.',
        exp:'Permiten cuantificar relaciones y predecir valores nuevos con incertidumbre estimada.',
        clave:['Predicción','Dosis-respuesta','Calibración'],
        flashcards:[['¿Una aplicación biológica de la regresión?','Modelar la relación dosis-respuesta de un fármaco.']] },
      { n:'Diseño experimental',
        def:'Planificación de experimentos para obtener datos válidos, controlando variables y usando aleatorización, repetición y bloqueo.',
        exp:'Principios de Fisher: aleatorización, repetición y control local (bloqueo). Un buen diseño reduce el sesgo y aumenta la potencia.',
        clave:['Aleatorización','Repetición','Bloqueo','Control'],
        examen:['Los 3 principios de Fisher: aleatorización, repetición y control local (bloqueo).'],
        flashcards:[['¿Cuáles son los principios del diseño experimental de Fisher?','Aleatorización, repetición y control local (bloqueo).']],
        preguntas:[['¿Cuál NO es un principio del diseño experimental de Fisher?',['Aleatorización','Repetición','Bloqueo','Sesgo'],3,'El sesgo es lo que se busca evitar, no un principio.']] },
      { n:'Aplicaciones (diseño experimental)',
        def:'Uso de diseños como el completamente al azar, bloques al azar y factoriales en investigación biológica.',
        exp:'Los diseños factoriales permiten estudiar varios factores y sus interacciones a la vez.',
        clave:['Completamente al azar','Bloques','Factorial','Interacción'],
        flashcards:[['¿Qué permite un diseño factorial?','Estudiar varios factores y sus interacciones simultáneamente.']] }
    ]}
  ]
};

// ============================================================
// 2) BIOLOGÍA DE HONGOS
// ============================================================
CONTENIDO.hongos = {
  nombre: 'Biología de Hongos', icono: '🍄',
  intro: 'Los hongos no son ni plantas ni animales: forman su propio reino. Descomponen, se asocian, curan y enferman. Estudiarlos es asomarse a una red oculta que sostiene los ecosistemas.',
  unidades: [
    { nombre: 'Unidad I. Introducción', temas: [
      { n:'Hifa',
        def:'Filamento tubular que constituye la unidad estructural básica del cuerpo de la mayoría de los hongos.',
        exp:'Las hifas pueden ser septadas (con tabiques) o cenocíticas (sin tabiques, multinucleadas). Crecen por su ápice y absorben nutrientes del medio.',
        clave:['Filamento','Septo','Cenocítica','Crecimiento apical'],
        cuadro:{head:['Tipo de hifa','Característica'],filas:[['Septada','Con tabiques transversales'],['Cenocítica','Sin septos, multinucleada']]},
        examen:['Hifa septada = con septos; cenocítica = sin septos.'],
        flashcards:[['¿Qué es una hifa?','El filamento tubular básico del cuerpo de un hongo.']],
        preguntas:[['Una hifa sin tabiques y multinucleada se llama:',['Septada','Cenocítica','Levaduriforme','Rizoide'],1,'Cenocítica = sin septos.']] },
      { n:'Micelio',
        def:'Conjunto o red de hifas que forma el cuerpo vegetativo del hongo.',
        exp:'El micelio explora el sustrato, absorbe nutrientes y puede diferenciarse para formar estructuras reproductoras (cuerpos fructíferos).',
        clave:['Red de hifas','Cuerpo vegetativo','Absorción'],
        ejemplos:['El “moho” blanco sobre el pan es micelio de Rhizopus.'],
        flashcards:[['¿Qué es el micelio?','La red de hifas que forma el cuerpo del hongo.']] },
      { n:'Espora',
        def:'Unidad de dispersión y reproducción de los hongos, generalmente unicelular y resistente.',
        exp:'Pueden ser sexuales o asexuales. Al germinar producen nuevas hifas. Su forma y origen son clave para la clasificación.',
        clave:['Dispersión','Germinación','Sexual/asexual'],
        examen:['El tipo de espora sexual define muchos grupos (asco- vs basidiosporas).'],
        flashcards:[['¿Función de las esporas fúngicas?','Dispersión y reproducción.']] },
      { n:'Levadura',
        def:'Hongo unicelular que se reproduce principalmente por gemación o fisión.',
        exp:'Muchas son ascomicetos (Saccharomyces). Realizan fermentación, base de la producción de pan, cerveza y vino.',
        clave:['Unicelular','Gemación','Fermentación'],
        ejemplos:['Saccharomyces cerevisiae en la elaboración de pan y cerveza.'],
        flashcards:[['¿Cómo se reproduce típicamente una levadura?','Por gemación.']] }
    ]},
    { nombre: 'Unidad II. Sistemática y Evolución', temas: [
      { n:'Oomicetos',
        def:'Organismos parecidos a hongos (“mohos acuáticos”) que en realidad pertenecen a los estramenópilos, no al reino Fungi.',
        exp:'Tienen pared de celulosa (no quitina) y esporas flageladas. Incluyen patógenos como Phytophthora infestans (tizón de la papa).',
        clave:['Pseudohongos','Celulosa','Estramenópilos','Phytophthora'],
        examen:['Los oomicetos NO son hongos verdaderos: pared de celulosa, no quitina.'],
        flashcards:[['¿¿Por qué los oomicetos no son hongos verdaderos?','Tienen pared de celulosa y son estramenópilos.']],
        preguntas:[['Los oomicetos se diferencian de los hongos verdaderos porque su pared es de:',['Quitina','Celulosa','Peptidoglicano','Lignina'],1,'Pared de celulosa, no quitina.']] },
      { n:'Mixomicetos',
        def:'“Mohos mucilaginosos”: protistas que forman plasmodios móviles y luego cuerpos fructíferos con esporas.',
        exp:'No son hongos verdaderos; se agrupan tradicionalmente con ellos por formar esporas. Fagocitan bacterias.',
        clave:['Plasmodio','Fagocitosis','Protista'],
        flashcards:[['¿Qué estructura móvil forman los mixomicetos?','Un plasmodio.']] },
      { n:'Chytridiomycota',
        def:'Hongos primitivos, en su mayoría acuáticos, cuyas esporas (zoosporas) tienen flagelo.',
        exp:'Son el único grupo de hongos verdaderos con células flageladas. Batrachochytrium causa la quitridiomicosis, letal para anfibios.',
        clave:['Zoosporas flageladas','Acuáticos','Batrachochytrium'],
        examen:['Chytridiomycota = únicos hongos con células flageladas.'],
        flashcards:[['¿Qué hace únicos a los quitridios?','Poseen esporas flageladas (zoosporas).']] },
      { n:'Zygomycota',
        def:'Hongos con hifas cenocíticas que forman zigosporas de pared gruesa en la reproducción sexual.',
        exp:'Incluyen mohos comunes como Rhizopus (moho del pan). Reproducción asexual por esporangios.',
        clave:['Zigospora','Cenocítica','Rhizopus'],
        flashcards:[['¿Estructura sexual de los Zygomycota?','La zigospora.']] },
      { n:'Glomeromycota',
        def:'Hongos que forman micorrizas arbusculares obligadas con las raíces de la mayoría de las plantas.',
        exp:'Penetran las células de la raíz formando arbúsculos donde intercambian fósforo por azúcares. Son biotrofos obligados.',
        clave:['Micorriza arbuscular','Arbúsculos','Simbiosis obligada'],
        examen:['Glomeromycota = micorrizas arbusculares (las más comunes).'],
        flashcards:[['¿Qué asociación forman los Glomeromycota?','Micorrizas arbusculares con raíces de plantas.']] },
      { n:'Ascomycota',
        def:'El grupo más grande de hongos; producen esporas sexuales (ascosporas) dentro de un saco llamado asca.',
        exp:'Incluyen levaduras, Penicillium, trufas y muchos líquenes. Gran importancia biotecnológica y médica.',
        clave:['Asca','Ascosporas','Penicillium'],
        cuadro:{head:['Grupo','Espora sexual','Estructura'],filas:[['Ascomycota','Ascosporas','Asca (saco)'],['Basidiomycota','Basidiosporas','Basidio']]},
        examen:['Ascomycota: ascosporas dentro de ascas.'],
        flashcards:[['¿Dónde se forman las ascosporas?','Dentro de un asca (saco).']] },
      { n:'Basidiomycota',
        def:'Hongos que producen esporas sexuales (basidiosporas) sobre una estructura en forma de maza llamada basidio.',
        exp:'Incluyen los champiñones, royas y carbones. Su cuerpo fructífero (seta) es el basidiocarpo.',
        clave:['Basidio','Basidiosporas','Seta'],
        examen:['Basidiomycota: basidiosporas sobre basidios (setas, royas, carbones).'],
        flashcards:[['¿Qué hongos comunes son Basidiomycota?','Los champiñones y setas.']] }
    ]},
    { nombre: 'Unidad III. Fisiología', temas: [
      { n:'Hongos saprobios',
        def:'Hongos que se nutren de materia orgánica muerta, descomponiéndola mediante enzimas extracelulares.',
        exp:'Son descomponedores clave: reciclan carbono y nutrientes. Digestión externa (secretan enzimas) y luego absorción.',
        clave:['Saprotrofia','Descomposición','Digestión externa','Reciclaje'],
        ejemplos:['Hongos que degradan la hojarasca y la madera caída del bosque.'],
        examen:['Nutrición fúngica = digestión externa + absorción.'],
        flashcards:[['¿Cómo se alimentan los hongos saprobios?','Digieren materia muerta con enzimas externas y absorben los nutrientes.']],
        preguntas:[['Los hongos realizan la digestión de forma:',['Interna','Externa','Fotosintética','Quimiosintética'],1,'Secretan enzimas al medio y luego absorben.']] },
      { n:'Micoparasitismo',
        def:'Modo de vida en que un hongo parasita a otro hongo.',
        exp:'Base de muchos agentes de control biológico (p. ej. Trichoderma ataca hongos fitopatógenos).',
        clave:['Hongo sobre hongo','Trichoderma','Control biológico'],
        flashcards:[['¿Qué es el micoparasitismo?','Cuando un hongo parasita a otro hongo.']] }
    ]},
    { nombre: 'Unidad IV. Genética', temas: [
      { n:'Micovirus',
        def:'Virus que infectan a los hongos y se transmiten principalmente por vía intracelular (no extracelular).',
        exp:'Pueden alterar la virulencia de hongos patógenos; algunos se investigan para el control biológico (hipovirulencia).',
        clave:['Virus de hongos','Hipovirulencia','Transmisión interna'],
        examen:['Los micovirus se transmiten intracelularmente, no por el exterior.'],
        flashcards:[['¿Qué son los micovirus?','Virus que infectan hongos, transmitidos intracelularmente.']] }
    ]},
    { nombre: 'Unidad V. Ecología', temas: [
      { n:'Líquenes',
        def:'Asociación simbiótica entre un hongo (micobionte) y un alga o cianobacteria (fotobionte).',
        exp:'El hongo aporta estructura y protección; el fotobionte, azúcares por fotosíntesis. Son bioindicadores de calidad del aire.',
        clave:['Simbiosis','Micobionte','Fotobionte','Bioindicador'],
        ejemplos:['Líquenes usados para evaluar contaminación atmosférica.'],
        examen:['Líquen = hongo + alga/cianobacteria; bioindicador de aire limpio.'],
        flashcards:[['¿Qué dos organismos forman un líquen?','Un hongo y un alga o cianobacteria.']],
        preguntas:[['En un líquen, el organismo fotosintético se llama:',['Micobionte','Fotobionte','Saprobio','Endófito'],1,'El fotobionte es el alga/cianobacteria.']] },
      { n:'Micorrizas',
        def:'Simbiosis mutualista entre hongos y las raíces de las plantas.',
        exp:'El hongo mejora la absorción de agua y fósforo; la planta aporta azúcares. Tipos: arbusculares (endo) y ectomicorrizas.',
        clave:['Mutualismo','Raíz','Fósforo','Ecto/endo'],
        cuadro:{head:['Tipo','Ubicación','Ejemplo'],filas:[['Arbuscular (endo)','Dentro de células','Glomeromycota'],['Ectomicorriza','Rodea la raíz','Muchos Basidiomycota']]},
        examen:['Micorriza = mutualismo hongo-raíz; mejora captación de fósforo.'],
        flashcards:[['¿Qué gana la planta en una micorriza?','Mayor absorción de agua y nutrientes (fósforo).']] },
      { n:'Endófitos',
        def:'Hongos que viven dentro de los tejidos vegetales sin causar daño aparente.',
        exp:'Pueden proteger a la planta produciendo compuestos que disuaden herbívoros o patógenos.',
        clave:['Interior del tejido','Protección','Simbiosis'],
        flashcards:[['¿Dónde viven los hongos endófitos?','Dentro de los tejidos de la planta, sin dañarla.']] }
    ]},
    { nombre: 'Unidad VI. Los hongos en las actividades humanas', temas: [
      { n:'Micosis',
        def:'Enfermedades causadas por hongos en humanos o animales.',
        exp:'Se clasifican en superficiales, cutáneas, subcutáneas y sistémicas. Ejemplos: pie de atleta, candidiasis.',
        clave:['Superficial','Sistémica','Candidiasis','Dermatofito'],
        examen:['Micosis sistémica = más grave, afecta órganos internos.'],
        flashcards:[['¿Qué es una micosis?','Una enfermedad causada por hongos.']] },
      { n:'Micotoxinas',
        def:'Metabolitos tóxicos producidos por hongos que contaminan alimentos.',
        exp:'La aflatoxina (Aspergillus) es carcinogénica; afecta granos y frutos secos mal almacenados.',
        clave:['Aflatoxina','Aspergillus','Contaminación de alimentos'],
        examen:['La aflatoxina es una micotoxina carcinogénica producida por Aspergillus.'],
        flashcards:[['¿Micotoxina más conocida y su productor?','Aflatoxina, producida por Aspergillus.']] },
      { n:'Etnomicología',
        def:'Estudio de las relaciones entre los hongos y las culturas humanas a lo largo del tiempo.',
        exp:'Abarca usos alimentarios, medicinales y rituales; en México destaca el uso tradicional de hongos comestibles y sagrados.',
        clave:['Cultura','Usos tradicionales','Hongos sagrados'],
        flashcards:[['¿Qué estudia la etnomicología?','La relación entre los hongos y las culturas humanas.']] },
      { n:'Biotecnología',
        def:'Uso de hongos para producir bienes: alimentos, bebidas, enzimas, antibióticos y ácidos orgánicos.',
        exp:'Penicillium produce penicilina; Saccharomyces, bebidas y pan; Aspergillus, ácido cítrico y enzimas industriales.',
        clave:['Penicilina','Fermentación','Enzimas','Ácido cítrico'],
        ejemplos:['Producción industrial de penicilina a partir de Penicillium chrysogenum.'],
        examen:['Penicillium → penicilina; primer antibiótico de origen fúngico.'],
        flashcards:[['¿Qué antibiótico produce Penicillium?','La penicilina.']],
        preguntas:[['El ácido cítrico industrial se obtiene principalmente de:',['Saccharomyces','Aspergillus','Rhizopus','Penicillium'],1,'Aspergillus niger es el productor industrial de ácido cítrico.']] },
      { n:'Control biológico',
        def:'Uso de hongos para combatir plagas, malezas u otros patógenos, reduciendo el uso de químicos.',
        exp:'Trichoderma controla hongos fitopatógenos; Beauveria y Metarhizium son hongos entomopatógenos que matan insectos plaga.',
        clave:['Trichoderma','Entomopatógenos','Beauveria','Plagas'],
        examen:['Beauveria y Metarhizium = hongos que controlan insectos plaga.'],
        flashcards:[['¿Hongo usado contra insectos plaga?','Beauveria bassiana (entomopatógeno).']] }
    ]}
  ]
};



